# 🐼 Pandas Part 2: DataFrames Masterclass
**From 1D Series to 2D Data Analysis Powerhouse**

Welcome to Part 2! Now that you've mastered the Pandas Series (a single column), it's time to combine them into a **DataFrame** (a full table). This notebook is structured to build your intuition, show you real-world applications, and test your knowledge immediately after every concept.

In [353]:
# ==========================================
# 🛠️ SETUP & MOCK DATA GENERATION
# ==========================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(f"🐼 Pandas Version: {pd.__version__}")

# 1. Mock Movies Data
movies_data = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\movies.csv")
movies = pd.DataFrame(movies_data)

# 2. Mock IPL Data
ipl_data = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\ipl-matches.csv")
ipl = pd.DataFrame(ipl_data)

print("✅ Mock Data Loaded Successfully!")

🐼 Pandas Version: 3.0.4
✅ Mock Data Loaded Successfully!

In [354]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [355]:
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

---
# 📘 Module 1: Creating DataFrames

A **DataFrame** is a 2-dimensional labeled data structure with columns of potentially different types. It is the most widely used object in Pandas.

## 💡 Mental Model
If a **Series** is a single column in an Excel spreadsheet, a **DataFrame** is the **entire spreadsheet**. You can create it from lists of lists (row by row), dictionaries (column by column), or external files (CSV).

## 📊 Visual Diagram
```text
1. List of Lists (Row-wise)          2. Dictionary (Column-wise)
   [ [1, 2], [3, 4] ]                  {'A': [1, 3], 'B': [2, 4]}
         ↓                                     ↓
   ┌───┬───┐                             ┌───┬───┐
   │ 0 │ 1 │                             │ A │ B │
   ├───┼───┤                             ├───┼───┤
   │ 1 │ 2 │                             │ 1 │ 2 │
   │ 3 │ 4 │                             │ 3 │ 4 │
   └───┴───┘                             └───┴───┘
```

## 🌍 Real-World Use Case
Reading a 50,000-row CSV file of customer transactions into a DataFrame so you can analyze spending patterns, filter by date, and calculate total revenue.

## ⚠️ Common Mistakes
When passing a dictionary, all lists (columns) **must be of the same length**. If one is shorter, Pandas will throw a `ValueError`.

## 🎤 Interview Questions
**Q: What happens if you pass a dictionary to `pd.DataFrame()` where one list is shorter than the others?**
**A:** Pandas will raise a `ValueError: All arrays must be of the same length`. You must ensure all columns have the same number of rows.

## 🎯 Practice Tasks

🟢 **Easy:** Create a DataFrame from a list of lists: `[[1, 'A'], [2, 'B']]` with columns `['num', 'char']`.

🟡 **Medium:** Create a DataFrame from a dictionary of 3 students and their ages.

🔴 **Hard:** Create a DataFrame from a dictionary, but set a custom index using the `index` parameter.

<details>
<summary>Click for Solution</summary>

```
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
# 1. Using List of Lists
student_data = [[100, 80, 10], [90, 70, 7], [120, 100, 14]]
df_list = pd.DataFrame(student_data, columns=['iq', 'marks', 'package'])
print("--- From List of Lists ---")
print(df_list)

# 2. Using Dictionary
student_dict = {'name': ['nitish', 'ankit'], 'iq': [100, 90], 'marks': [80, 70]}
df_dict = pd.DataFrame(student_dict)
print("\n--- From Dictionary ---")
print(df_dict)

# 3. Using read_csv (Simulated with io.StringIO)
import io
csv_data = "title_x,year\n3 Idiots,2009\nPK,2014"
df_csv = pd.read_csv(io.StringIO(csv_data))
print("\n--- From CSV ---")
print(df_csv)
```

</details>

In [356]:

# This is a list of lists (a 2D list). 
# Each inner list represents one complete ROW of data for a single student.
student_data = [
    [100, 80, 10],  # Row 0: Student 1's IQ, marks, and package
    [90, 40, 41],   # Row 1: Student 2's data
    [120, 100, 14]  # Row 2: Student 3's data
]

# pd.DataFrame() converts the raw data into a structured 2D table.
# The 'columns' argument is required here to give names to the columns, 
# otherwise pandas will just name them 0, 1, 2 by default.
df_from_list = pd.DataFrame(student_data, columns=["iq", "marks", "package"])

print(df_from_list)

    iq  marks  package
0  100     80       10
1   90     40       41
2  120    100       14

In [357]:
# This is a standard Python dictionary.
# The KEYS will automatically become the column headers.
# The VALUES are lists containing all the data for that specific column.
student_dict = {
    "iq": [100, 90, 120],       # All the IQ scores (Column 1)
    "marks": [80, 40, 100],     # All the marks (Column 2)
    "package": [10, 41, 14]     # All the packages (Column 3)
}

# When passing a dictionary, pandas is smart enough to use the keys as column names.
# You do NOT need the 'columns' argument here.
df_from_dict = pd.DataFrame(student_dict)

print(df_from_dict)

    iq  marks  package
0  100     80       10
1   90     40       41
2  120    100       14

In [358]:
# pd.read_csv() reads the file and returns a DataFrame.
# (Note: The 'r' before the string stands for "raw string". It tells Python to ignore 
# escape characters like '\n' or '\t', which is highly recommended for Windows file paths!)
students = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\students.csv")
print(students.head())
# This takes the existing "name" column and moves it to become the row index.
# inplace=True means it modifies the 'students' DataFrame directly in memory, 
# rather than returning a new, modified copy.
students.set_index('student_id', inplace=True)
print(students.head())

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3
3           4     Marlo Dugal       14
4           5     Kusum Bahri        6
                      name  partner
student_id
1            Kailash Harjo       23
2              Esha Butala        1
3           Parveen Bhalla        3
4              Marlo Dugal       14
5              Kusum Bahri        6

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 1)
# ==========================================
# 🟢 Easy
print(pd.DataFrame([[1, 'A'], [2, 'B']], columns=['num', 'char']))

# 🟡 Medium
print(pd.DataFrame({'student': ['Ali', 'Ben', 'Cat'], 'age': [20, 22, 21]}))

# 🔴 Hard
print(pd.DataFrame({'score': [90, 85]}, index=['exam1', 'exam2']))

```

</details>

In [359]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 1)
# ==========================================
# 🟢 Easy: Create a DataFrame from a list of lists: [[1, 'A'], [2, 'B']] with columns ['num', 'char']
# YOUR CODE HERE:


# 🟡 Medium: Create a DataFrame from a dictionary of 3 students and their ages
# YOUR CODE HERE:


# 🔴 Hard: Create a DataFrame from a dictionary, but set a custom index using the `index` parameter
# YOUR CODE HERE:

# 📘 Module 2: Attributes & Exploratory Methods

**Attributes** (no parentheses) give you metadata about the DataFrame. **Methods** (with parentheses) perform actions like viewing data, summarizing statistics, or checking for missing values.

## 💡 Mental Model
Attributes are the DataFrame's **ID Card** (How big is it? What types are the columns?). Methods are the DataFrame's **Tools** (Show me the top 5 rows! Summarize the math!).

## 📊 Visual Diagram
```text
DataFrame
 ├── Attributes (No parentheses)
 │    ├── shape: (rows, cols)
 │    ├── dtypes: data types per column
 │    └── columns: list of column names
 └── Methods (Parentheses)
      ├── info(): memory usage & non-null counts
      ├── describe(): statistical summary (mean, std, min, max)
      └── isnull().sum(): count missing values per column
```

## 🌍 Real-World Use Case
Before training a Machine Learning model, you run `df.info()` and `df.isnull().sum()` to ensure you have enough data and to identify which columns need missing-value imputation.

## ⚠️ Common Mistakes
Forgetting that `describe()` only works on **numeric** columns by default. To see summaries for strings/objects, you must pass `include='all'`.

## 🎤 Interview Questions
**Q: What is the difference between `df.shape` and `df.info()`?**
> **A:** `df.shape` returns a simple tuple `(rows, columns)`. `df.info()` prints a detailed summary including column names, non-null counts, data types, and total memory usage.

In [360]:
# Returns a tuple in the format: (number_of_rows, number_of_columns)
# Example output: (1000, 5) meaning 1000 rows and 5 columns.
print(movies.shape, ipl.shape, students.shape)

(1629, 18) (950, 20) (25, 2)

In [361]:
# Returns a list of all columns and their specific data types.
# Common types include 'int64' (whole numbers), 'float64' (decimals), 
# and 'object' (strings/text).
print(movies.dtypes)

title_x                 str
imdb_id                 str
poster_path             str
wiki_link               str
title_y                 str
original_title          str
is_adult              int64
year_of_release       int64
runtime                 str
genres                  str
imdb_rating         float64
imdb_votes            int64
story                   str
summary                 str
tagline                 str
actors                  str
wins_nominations        str
release_date            str
dtype: object

In [362]:
# Returns the row labels. 
# If you haven't set a custom index, it will usually say RangeIndex(start=0, stop=..., step=1).
# If you set custom labels (like movie names), it will list those names.
print(students.index, ipl.index, sep="\n\n")

RangeIndex(start=1, stop=26, step=1, name='student_id')

RangeIndex(start=0, stop=950, step=1)

In [363]:
# Returns an Index object (which acts like a list) of all column names.
print(movies.columns, ipl.columns, students.columns, sep="\n\n")

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

Index(['name', 'partner'], dtype='str')

In [364]:
# Returns the pure data as a 2-Dimensional NumPy array (a grid of data).
print(students.values, ipl.values, sep="\n\n")

[['Kailash Harjo' 23]
 ['Esha Butala' 1]
 ['Parveen Bhalla' 3]
 ['Marlo Dugal' 14]
 ['Kusum Bahri' 6]
 ['Lakshmi Contractor' 10]
 ['Tarun Thaker' 9]
 ['Radheshyam Dey' 5]
 ['Nitika Chatterjee' 4]
 ['Aayushman Sant' 8]
 ['David Mukhopadhyay' 20]
 ['Radha Dutt' 19]
 ['Munni Varghese' 24]
 ['Pranab Natarajan' 22]
 ['Preet Sha' 16]
 ['Elias Dodiya' 25]
 ['Yasmin Palan' 7]
 ['Fardeen Mahabir' 13]
 ['Qabeel Raman' 12]
 ['Hanuman Hegde' 11]
 ['Seema Kota' 15]
 ['Yash Sethi' 21]
 ['Chhavi Lachman' 18]
 ['Radhika Suri' 17]
 ['Shashank D’Alia' 2]]

[[1312200 'Ahmedabad' '2022-05-29' ...
  "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"
  'CB Gaffaney' 'Nitin Menon']
 [1312199 'Ahmedabad' '2022-05-27' ...
  "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']"
  'CB Gaffaney' 'Nitin Menon']
 [1312198 'Kolkata' '2022-05-25' ...
  "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']"
  'J Madanagopal' 'MA Gough']
 ...
 [335984 'Delhi' '2008-04-19' ...
  "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']"
  'Aleem Dar' 'GA Pratapkumar']
 [335983 'Chandigarh' '2008-04-19' ...
  "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']"
  'MR Benson' 'SL Shastri']
 [335982 'Bangalore' '2008-04-18' ...
  "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']"
  'Asad Rauf' 'RE Koertzen']]

In [365]:
# Returns the first 5 rows of the DataFrame by default.
# You can pass a number inside the parentheses to see more/less (e.g., movies.head(10)).
print(movies.head())

                                title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224
1                         Battalion 609  tt9472208
2  The Accidental Prime Minister (film)  tt6986710
3                       Why Cheat India  tt8108208
4                       Evening Shadows  tt6028796

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN
2  https://upload.wikimedia.org/wikipedia/en/thum...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4                                                NaN

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1        https://en.wikipedia.org/wiki/Battalion_609
2  https://en.wikipedia.org/wiki/The_Accidental_P...
3      https://en.wikipedia.org/wiki/Why_Cheat_India
4      https://en.wikipedia.org/wiki/Evening_Shadows

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                  Battalion 609                  Battalion 609         0
2  The Accidental Prime Minister  The Accidental Prime Minister         0
3                Why Cheat India                Why Cheat India         0
4                Evening Shadows                Evening Shadows         0

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112
1             2019     131               War          4.1          73
2             2019     112   Biography|Drama          6.1        5549
3             2019     121       Crime|Drama          6.0        1891
4             2018     102             Drama          7.3         280

                                               story  \
0  Divided over five chapters  the film chronicle...
1  The story revolves around a cricket match betw...
2  Based on the memoir by Indian policy analyst S...
3  The movie focuses on existing malpractices in ...
4  While gay rights and marriage equality has bee...

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN
1  The story of Battalion 609 revolves around a c...     NaN
2  Explores Manmohan Singh's tenure as the Prime ...     NaN
3  The movie focuses on existing malpractices in ...     NaN
4  Under the 'Evening Shadows'  truth often plays...     NaN

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination

              release_date
0    11 January 2019 (USA)
1  11 January 2019 (India)
2    11 January 2019 (USA)
3    18 January 2019 (USA)
4  11 January 2019 (India)

In [366]:
# Returns the last 5 rows of the DataFrame by default.
print(movies.tail())

                    title_x     imdb_id  \
1624  Tera Mera Saath Rahen   tt0301250
1625   Yeh Zindagi Ka Safar   tt0298607
1626        Sabse Bada Sukh   tt0069204
1627                  Daaka  tt10833860
1628               Humsafar   tt2403201

                                            poster_path  \
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...
1625  https://upload.wikimedia.org/wikipedia/en/thum...
1626                                                NaN
1627  https://upload.wikimedia.org/wikipedia/en/thum...
1628  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh
1627                https://en.wikipedia.org/wiki/Daaka
1628             https://en.wikipedia.org/wiki/Humsafar

                    title_y         original_title  is_adult  year_of_release  \
1624  Tera Mera Saath Rahen  Tera Mera Saath Rahen         0             2001
1625   Yeh Zindagi Ka Safar   Yeh Zindagi Ka Safar         0             2001
1626        Sabse Bada Sukh        Sabse Bada Sukh         0             2018
1627                  Daaka                  Daaka         0             2019
1628               Humsafar               Humsafar         0             2011

     runtime         genres  imdb_rating  imdb_votes  \
1624     148          Drama          4.9         278
1625     146          Drama          3.0         133
1626      \N   Comedy|Drama          6.1          13
1627     136         Action          7.4          38
1628      35  Drama|Romance          9.0        2968

                                                  story  \
1624  Raj Dixit lives with his younger brother  Rahu...
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...
1626  Village born Lalloo re-locates to Bombay  and ...
1627  Shinda tries robbing a bank so he can be wealt...
1628  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
1624  A man is torn between his handicapped brother ...     NaN
1625  A singer finds out she was adopted when the ed...     NaN
1626  Village born Lalloo re-locates to Bombay  and ...     NaN
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                                                 actors wins_nominations  \
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...              NaN
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...              NaN
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...              NaN
1627                          Gippy Grewal|Zareen Khan|              NaN
1628                                        Fawad Khan|              NaN

                  release_date
1624   7 November 2001 (India)
1625  16 November 2001 (India)
1626                       NaN
1627     1 November 2019 (USA)
1628     TV Series (2011–2012)

In [367]:
# Returns 1 completely random row by default.
# You can ask for more rows (e.g., movies.sample(5)).
print(movies.sample())

                title_x    imdb_id  \
279  Nil Battey Sannata  tt5005684

                                           poster_path  \
279  https://upload.wikimedia.org/wikipedia/en/thum...

                                            wiki_link             title_y  \
279  https://en.wikipedia.org/wiki/Nil_Battey_Sannata  Nil Battey Sannata

         original_title  is_adult  year_of_release runtime        genres  \
279  Nil Battey Sannata         0             2015     100  Drama|Family

     imdb_rating  imdb_votes  \
279          8.4        4530

                                                 story  \
279  Appu is a class 10th student and is giving up ...

                                               summary tagline  \
279  A story about a single women (a Mom) and dream...     NaN

                                                actors       wins_nominations  \
279  Swara Bhaskar|Ratna Pathak Shah|Riya Shukla|Pa...  5 wins & 1 nomination

              release_date
279  22 April 2016 (India)

In [368]:
print(ipl.sample())

         ID    City        Date Season MatchNumber  \
47  1304073  Mumbai  2022-04-16   2022          27

                          Team1           Team2                     Venue  \
47  Royal Challengers Bangalore  Delhi Capitals  Wankhede Stadium, Mumbai

        TossWinner TossDecision SuperOver                  WinningTeam WonBy  \
47  Delhi Capitals        field         N  Royal Challengers Bangalore  Runs

    Margin method Player_of_Match  \
47    16.0    NaN      KD Karthik

                                         Team1Players  \
47  ['F du Plessis', 'Anuj Rawat', 'V Kohli', 'GJ ...

                                         Team2Players                Umpire1  \
47  ['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...  Chirra Ravikanthreddy

          Umpire2
47  J Madanagopal

In [369]:
print(students.sample)

<bound method NDFrame.sample of                           name  partner
student_id
1                Kailash Harjo       23
2                  Esha Butala        1
3               Parveen Bhalla        3
4                  Marlo Dugal       14
5                  Kusum Bahri        6
6           Lakshmi Contractor       10
7                 Tarun Thaker        9
8               Radheshyam Dey        5
9            Nitika Chatterjee        4
10              Aayushman Sant        8
11          David Mukhopadhyay       20
12                  Radha Dutt       19
13              Munni Varghese       24
14            Pranab Natarajan       22
15                   Preet Sha       16
16                Elias Dodiya       25
17                Yasmin Palan        7
18             Fardeen Mahabir       13
19                Qabeel Raman       12
20               Hanuman Hegde       11
21                  Seema Kota       15
22                  Yash Sethi       21
23              Chhavi Lachman       18
24                Radhika Suri       17
25             Shashank D’Alia        2>

In [370]:
# Prints the column names, the data type of each column, memory usage, 
# and how many "non-null" (non-empty) values exist in each column.
print(movies.info())

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB
None

In [371]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 1 to 25
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     25 non-null     str
 1   partner  25 non-null     int64
dtypes: int64(1), str(1)
memory usage: 532.0 bytes

In [372]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [373]:
# Calculates the count, mean, standard deviation, minimum, maximum, 
# and percentiles (25%, 50%, 75%) for every column containing numbers.
print(movies.describe())

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [374]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [375]:
# Returns a DataFrame of the exact same size, but filled entirely with 
# True (if the data is missing/NaN) or False (if the data exists).
print(movies.isnull())

      title_x  imdb_id  poster_path  wiki_link  title_y  original_title  \
0       False    False        False      False    False           False
1       False    False         True      False    False           False
2       False    False        False      False    False           False
3       False    False        False      False    False           False
4       False    False         True      False    False           False
...       ...      ...          ...        ...      ...             ...
1624    False    False        False      False    False           False
1625    False    False        False      False    False           False
1626    False    False         True      False    False           False
1627    False    False        False      False    False           False
1628    False    False        False      False    False           False

      is_adult  year_of_release  runtime  genres  imdb_rating  imdb_votes  \
0        False            False    False   False        False       False
1        False            False    False   False        False       False
2        False            False    False   False        False       False
3        False            False    False   False        False       False
4        False            False    False   False        False       False
...        ...              ...      ...     ...          ...         ...
1624     False            False    False   False        False       False
1625     False            False    False   False        False       False
1626     False            False    False   False        False       False
1627     False            False    False   False        False       False
1628     False            False    False   False        False       False

      story  summary  tagline  actors  wins_nominations  release_date
0     False    False     True   False             False         False
1     False    False     True   False              True         False
2     False    False     True   False              True         False
3     False    False     True   False              True         False
4     False    False     True   False             False         False
...     ...      ...      ...     ...               ...           ...
1624  False    False     True   False              True         False
1625  False    False     True   False              True         False
1626  False    False     True   False              True          True
1627  False    False     True   False              True         False
1628  False    False     True   False              True         False

[1629 rows x 18 columns]

In [376]:
print(students.isnull().sum())

name       0
partner    0
dtype: int64

In [377]:
# Returns a Series of True/False values. 
# It marks False for the first time it sees a row, and True if it sees 
# that exact same row repeated further down the dataset.
print(movies.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In [378]:
print(students.duplicated().sum())

0

In [379]:
# The .rename() method is used to change row labels or column headers.
# By passing the 'columns' argument, we tell pandas exactly what we want to change.
# We provide a dictionary where the KEY is the old name, and the VALUE is the new name.

students.rename(columns={
    "marks": "percent",  # Finds the column "marks" and renames it to "percent"
    "package": "lpa"     # Finds the column "package" and renames it to "lpa"
})

                          name  partner
student_id
1                Kailash Harjo       23
2                  Esha Butala        1
3               Parveen Bhalla        3
4                  Marlo Dugal       14
5                  Kusum Bahri        6
6           Lakshmi Contractor       10
7                 Tarun Thaker        9
8               Radheshyam Dey        5
9            Nitika Chatterjee        4
10              Aayushman Sant        8
11          David Mukhopadhyay       20
12                  Radha Dutt       19
13              Munni Varghese       24
14            Pranab Natarajan       22
15                   Preet Sha       16
16                Elias Dodiya       25
17                Yasmin Palan        7
18             Fardeen Mahabir       13
19                Qabeel Raman       12
20               Hanuman Hegde       11
21                  Seema Kota       15
22                  Yash Sethi       21
23              Chhavi Lachman       18
24                Radhika Suri       17
25             Shashank D’Alia        2

## 🎯 Practice Tasks

🟢 **Easy:** Find the `shape` and `columns` of the `movies` DataFrame.

🟡 **Medium:** Check how many missing values exist in every column of `ipl`.

🔴 **Hard:** Rename the `iq` column in `students` to `IQ_Score` and the `package` column to `LPA`.

<details>
<summary>Click for solution</summary>

```
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
print(f"Shape: {movies.shape}")
print(f"Columns: {movies.columns.tolist()}")
print(f"Dtypes:\n{movies.dtypes}\n")

# info() and describe()
print("--- Info ---")
ipl.info()

print("\n--- Describe ---")
print(movies.describe())

# Checking missing values and duplicates
print(f"\nNulls per column:\n{movies.isnull().sum()}")
print(f"\nDuplicate rows: {movies.duplicated().sum()}")

# Renaming columns
students.rename(columns={'iq': 'IQ_Score', 'package': 'LPA'}, inplace=True)
print(f"\nRenamed Columns: {students.columns.tolist()}")
```

</details>

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 2)
# ==========================================
# 🟢 Easy
print(movies.shape, movies.columns)

# 🟡 Medium
print(ipl.isnull().sum())

# 🔴 Hard
students.rename(columns={'iq': 'IQ_Score', 'package': 'LPA'}, inplace=True)
print(students.columns)

```

</details>

In [380]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 2)
# ==========================================
# 🟢 Easy: Find the shape and columns of the `movies` DataFrame
# YOUR CODE HERE:


# 🟡 Medium: Check how many missing values exist in every column of `ipl`
# YOUR CODE HERE:


# 🔴 Hard: Rename the 'iq' column in `students` to 'IQ_Score' and 'package' to 'LPA'
# YOUR CODE HERE:

# 📘 Module 3: Mathematical Methods & The `axis` Parameter

Pandas allows you to perform aggregate math (`sum`, `mean`, `var`) across the entire DataFrame. The most crucial concept here is the **`axis`** parameter.

## 💡 Mental Model
- **`axis=0`** means "pointing DOWN". It collapses rows together, applying the math to **each column**.
- **`axis=1`** means "pointing SIDEWAYS". It collapses columns together, applying the math to **each row**.

## 📊 Visual Diagram
```text
       Col1  Col2
Row1 [ 10,   20 ]  -> axis=1 (sum=30)
Row2 [ 30,   40 ]  -> axis=1 (sum=70)
       ↓      ↓
    axis=0   axis=0
   (sum=40) (sum=60)
```

## 🌍 Real-World Use Case
Calculating the **total marks per student** (sum across columns, `axis=1`) vs calculating the **class average per subject** (mean across rows, `axis=0`).

## ⚠️ Common Mistakes
Confusing `axis=0` and `axis=1`. Remember: `axis=0` operates *down* the index (rows), `axis=1` operates *across* the columns.

## 🎤 Interview Questions
**Q: If you run `df.sum(axis=1)`, what does the output represent?**
**A:** It returns a Series where each value is the sum of the columns for that specific row. The length of the output Series equals the number of rows in the DataFrame.

## 🎯 Practice Tasks

🟢 **Easy:** Calculate the sum of all numeric columns in `students` (default axis).

🟡 **Medium:** Calculate the mean of `iq` and `marks` for **each student** (row-wise).

🔴 **Hard:** Calculate the variance (`var()`) of the numeric columns in `students` across columns.

In [381]:
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
# Reset students columns for this example
students.rename(columns={'IQ_Score': 'iq', 'LPA': 'package'}, inplace=True)

# axis=0 (Default) -> Sum of each column
print("--- Sum of Columns (axis=0) ---")
# print(students.sum(axis=0))

# axis=1 -> Sum of each row
print("\n--- Sum of Rows (axis=1) ---")
# print(students.sum(axis=1))

# Mean across rows
print("\n--- Mean of IQ and Marks per student ---")
# print(students[['iq', 'marks']].mean(axis=1))

--- Sum of Columns (axis=0) ---

--- Sum of Rows (axis=1) ---

--- Mean of IQ and Marks per student ---

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 3)
# ==========================================
# 🟢 Easy
print(students.sum()) # axis=0 is default

# 🟡 Medium
print(students[['iq', 'marks']].mean(axis=1))

# 🔴 Hard
print(students.var())


```

</details>

In [382]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 3)
# ==========================================
# 🟢 Easy: Calculate the sum of all numeric columns in `students`
# YOUR CODE HERE:


# 🟡 Medium: Calculate the mean of `iq` and `marks` for EACH student (row-wise)
# YOUR CODE HERE:


# 🔴 Hard: Calculate the variance (var()) of the numeric columns in `students`
# YOUR CODE HERE:

# 📘 Module 4: Selecting Rows & Columns (`loc` vs `iloc`)

You can extract specific columns using brackets `[]`. To extract rows, or both rows and columns simultaneously, you use **`iloc`** (integer position) and **`loc`** (label-based).

## 💡 Mental Model
- **`iloc`** is like a Python List. It uses **0-based integer positions**. (e.g., "Give me the 3rd row").
- **`loc`** is like a Python Dictionary. It uses the **actual index labels**. (e.g., "Give me the row named 'anuj'").

## 📊 Visual Diagram
```text
       Col1  Col2
RowA [ 10,   20 ]
RowB [ 30,   40 ]

iloc[0, 1] -> 20 (Position 0, Position 1)
loc['RowA', 'Col2'] -> 20 (Label 'RowA', Label 'Col2')
```

## 🌍 Real-World Use Case
Extracting the `Team1` and `Team2` columns for the first 5 matches (`iloc[:5, [2,3]]`) to display a quick preview on a dashboard.

## ⚠️ Common Mistakes
Using `loc` with integer positions when your index is strings. If your index is `['a', 'b', 'c']`, `loc[0]` will throw a `TypeError` because `0` is not a label!

## 🎤 Interview Questions
**Q: What is the difference in slicing behavior between `loc` and `iloc`?**
> **A:** `iloc` slicing is **exclusive** of the end index (like standard Python lists: `0:3` gets 0, 1, 2). `loc` slicing is **inclusive** of the end label (`'a':'c'` gets 'a', 'b', and 'c').

In [383]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [384]:
# Fetching single column
movies["title_x"]

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: str

In [385]:
# fetching multiple colums
movies[
    [
        "title_x", 
        "year_of_release", 
        "actors"
    ]
]

,title_x,year_of_release,actors
0,Uri: The Surgical Strike,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,2019,Gippy Grewal|Zareen Khan|
1628,Humsafar,2011,Fawad Khan|

In [386]:
iplmod = ipl[
    ["Team1", "Team2", "WinningTeam"]
]
display(iplmod)
iplmod.set_index("WinningTeam", inplace=True)
display(iplmod)

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

,Team1,Team2
WinningTeam,,
Gujarat Titans,Rajasthan Royals,Gujarat Titans
Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals
Royal Challengers Bangalore,Royal Challengers Bangalore,Lucknow Super Giants
Gujarat Titans,Rajasthan Royals,Gujarat Titans
Punjab Kings,Sunrisers Hyderabad,Punjab Kings
...,...,...
Kolkata Knight Riders,Kolkata Knight Riders,Deccan Chargers
Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore
Delhi Daredevils,Delhi Daredevils,Rajasthan Royals
Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders

In [387]:
# single Row, for single row it is series
iplmod.iloc[0]

Team1    Rajasthan Royals
Team2      Gujarat Titans
Name: Gujarat Titans, dtype: str

In [388]:
ipl.iloc[0]

ID                                                           1312200
City                                                       Ahmedabad
Date                                                      2022-05-29
Season                                                          2022
MatchNumber                                                    Final
Team1                                               Rajasthan Royals
Team2                                                 Gujarat Titans
Venue                               Narendra Modi Stadium, Ahmedabad
TossWinner                                          Rajasthan Royals
TossDecision                                                     bat
SuperOver                                                          N
WinningTeam                                           Gujarat Titans
WonBy                                                        Wickets
Margin                                                           7.0
method                                                           NaN
Player_of_Match                                            HH Pandya
Team1Players       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Team2Players       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
Umpire1                                                  CB Gaffaney
Umpire2                                                  Nitin Menon
Name: 0, dtype: object

In [389]:
# multiple rows, it is dataframe
iplmod.iloc[0:5]

                                                   Team1                 Team2
WinningTeam
Gujarat Titans                          Rajasthan Royals        Gujarat Titans
Rajasthan Royals             Royal Challengers Bangalore      Rajasthan Royals
Royal Challengers Bangalore  Royal Challengers Bangalore  Lucknow Super Giants
Gujarat Titans                          Rajasthan Royals        Gujarat Titans
Punjab Kings                         Sunrisers Hyderabad          Punjab Kings

In [390]:
# fancy

ipl.iloc[
    [2, 4, 7]
]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer

In [391]:
# Fetching Rows and Columns simultaneously
movies.iloc[0:3, 0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [392]:
# Fetching Rows and Columns simultaneously
movies.loc[0:3, "title_x":"poster_path"]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...

## 🎯 Practice Tasks

🟢 **Easy:** Extract the `title_x` and `imdb_rating` columns from `movies`.

🟡 **Medium:** Extract the 2nd and 4th rows of `movies` using `iloc`.

🔴 **Hard:** Extract rows 'nitish' to 'rupesh' (inclusive) and only the `iq` and `marks` columns using `loc`.

In [393]:
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
# 1. Selecting Columns
print("--- Single Column ---")
print(movies['title_x'].head(2))

print("\n--- Multiple Columns ---")
print(movies[['title_x', 'imdb_rating']].head(2))

# 2. Selecting Rows with iloc (Positions)
print("\n--- iloc (Positions) ---")
print("Single row:\n", movies.iloc[0])
print("Fancy indexing:\n", movies.iloc[[0, 2, 4]])

# 3. Selecting Rows with loc (Labels)
print("\n--- loc (Labels) ---")
print("Single row:\n", students.loc['nitish'])
print("Slicing (Inclusive!):\n", students.loc['nitish':'rupesh'])

# 4. Selecting Both Rows and Cols
print("\n--- Both Rows & Cols ---")
print("iloc[0:2, 0:2]:\n", movies.iloc[0:2, 0:2])
print("loc['nitish':'ankit', 'iq':'marks']:\n", students.loc['nitish':'ankit', 'iq':'marks'])

--- Single Column ---
0    Uri: The Surgical Strike
1               Battalion 609
Name: title_x, dtype: str

--- Multiple Columns ---
                    title_x  imdb_rating
0  Uri: The Surgical Strike          8.4
1             Battalion 609          4.1

--- iloc (Positions) ---
Single row:
 title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object
Fancy indexing:
                                 title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224
2  The Accidental Prime Minister (film)  tt6986710
4                       Evening Shadows  tt6028796

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
2  https://upload.wikimedia.org/wikipedia/en/thum...
4                                                NaN

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
2  https://en.wikipedia.org/wiki/The_Accidental_P...
4      https://en.wikipedia.org/wiki/Evening_Shadows

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0
2  The Accidental Prime Minister  The Accidental Prime Minister         0
4                Evening Shadows                Evening Shadows         0

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112
2             2019     112   Biography|Drama          6.1        5549
4             2018     102             Drama          7.3         280

                                               story  \
0  Divided over five chapters  the film chronicle...
2  Based on the memoir by Indian policy analyst S...
4  While gay rights and marriage equality has bee...

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN
2  Explores Manmohan Singh's tenure as the Prime ...     NaN
4  Under the 'Evening Shadows'  truth often plays...     NaN

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination

              release_date
0    11 January 2019 (USA)
2    11 January 2019 (USA)
4  11 January 2019 (India)

--- loc (Labels) ---

KeyError: 'nitish'

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 4)
# ==========================================
# 🟢 Easy
print(movies[['title_x', 'imdb_rating']])

# 🟡 Medium
print(movies.iloc[[1, 3]]) # 2nd is index 1, 4th is index 3

# 🔴 Hard
print(students.loc['nitish':'rupesh', ['iq', 'marks']])

```

</details>

In [ ]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 4)
# ==========================================
# 🟢 Easy: Extract the `title_x` and `imdb_rating` columns from `movies`
# YOUR CODE HERE:


# 🟡 Medium: Extract the 2nd and 4th rows of `movies` using `iloc`
# YOUR CODE HERE:


# 🔴 Hard: Extract rows 'nitish' to 'rupesh' (inclusive) and only the `iq` and `marks` columns using `loc`
# YOUR CODE HERE:

# 📘 Module 5: Filtering DataFrames (Boolean Indexing)

Filtering allows you to extract rows that meet specific conditions. You create a **Boolean Mask** (a Series of True/False) and pass it inside the DataFrame brackets `df[mask]`.

## 💡 Mental Model
Think of the mask as a **bouncer at a club**. The condition checks every row. If `True`, the row gets in. If `False`, it's filtered out. For multiple conditions, use `&` (AND), `|` (OR), and `~` (NOT).

## 📊 Visual Diagram
```text
Data:  [10, 50, 100]
Mask:  [F,  T,  T ]  (Data > 40)
Result:[50, 100]

Multiple Conditions:
(Data > 40) & (Data < 80) -> [F, T, F] & [T, F, F] -> [F, F, F]
```

## 🌍 Real-World Use Case
Finding all IPL finals where CSK won in Kolkata: `ipl[(ipl['WinningTeam'] == 'CSK') & (ipl['City'] == 'Kolkata')]`.

## ⚠️ Common Mistakes
Using Python's `and` / `or` instead of Pandas' `&` / `|`. Also, forgetting to wrap conditions in parentheses: `(df['A'] > 5) & (df['B'] < 10)`.

## 🎤 Interview Questions
**Q: How do you filter a DataFrame based on a partial string match in a column?**
**A:** Use the `.str.contains()` method. Example: `df[df['genres'].str.contains('Action')]`.

In [ ]:
# find all the IPL final winners
# print(ipl.head())
iplFinal = ipl["MatchNumber"] == "Final"
iplWinners = ipl[iplFinal]
iplWinners[
    ["Season", "WinningTeam"]
]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [ ]:
# how many super over finishes have occured
iplSuperOvers = ipl["SuperOver"] == "Y"
iplSuperOvers.sum()

np.int64(14)

In [ ]:
# how many matches has csk won in kolkata
iplKolkata = ipl["Venue"] == "Eden Gardens, Kolkata"
iplCSK = ipl[iplKolkata]["WinningTeam"] == "Chennai Super Kings"
iplCSK.sum()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
19,1304101,Navi Mumbai,2022-05-08,2022,55,Chennai Super Kings,Delhi Capitals,"Eden Gardens, Kolkata",Delhi Capitals,field,N,Chennai Super Kings,Runs,91.0,NaN,DP Conway,"['RD Gaikwad', 'DP Conway', 'S Dube', 'AT Rayu...","['DA Warner', 'KS Bharat', 'MR Marsh', 'RR Pan...",Nitin Menon,R Pandit
28,1304092,Pune,2022-05-01,2022,46,Chennai Super Kings,Sunrisers Hyderabad,"Eden Gardens, Kolkata",Sunrisers Hyderabad,field,N,Chennai Super Kings,Runs,13.0,NaN,RD Gaikwad,"['RD Gaikwad', 'DP Conway', 'MS Dhoni', 'RA Ja...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",AK Chaudhary,KN Ananthapadmanabhan
41,1304079,Navi Mumbai,2022-04-21,2022,33,Mumbai Indians,Chennai Super Kings,"Eden Gardens, Kolkata",Chennai Super Kings,field,N,Chennai Super Kings,Wickets,3.0,NaN,Mukesh Choudhary,"['RG Sharma', 'Ishan Kishan', 'D Brevis', 'SA ...","['RD Gaikwad', 'RV Uthappa', 'MJ Santner', 'AT...",BNJ Oxenford,UV Gandhe
52,1304068,Mumbai,2022-04-12,2022,22,Chennai Super Kings,Royal Challengers Bangalore,"Eden Gardens, Kolkata",Royal Challengers Bangalore,field,N,Chennai Super Kings,Runs,23.0,NaN,S Dube,"['RD Gaikwad', 'RV Uthappa', 'MM Ali', 'S Dube...","['F du Plessis', 'Anuj Rawat', 'V Kohli', 'GJ ...",Nitin Menon,N Pandit
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,"Eden Gardens, Kolkata",Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth

In [ ]:
ipl[(ipl["Venue"] == "Eden Gardens, Kolkata") & (["WinningTeam"] == "Chennai Super Kings")].shape

(0, 20)

In [ ]:
# toss winner is match winner in percentage

iplTossWinners = ipl["TossWinner"] == ipl["WinningTeam"]
TossWinningPercent = (iplTossWinners.sum() / ipl.shape[0]) * 100

print(ipl.shape[0], iplTossWinners.sum(), TossWinningPercent)

950 489 51.473684210526315

In [ ]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [ ]:
# movies with rating higher than 8 and votes>10000
moviesRatingBeyondEight = (movies["imdb_rating"] > 8) & (movies["imdb_votes"] > 10000)
# moviesInQuestin = movies[moviesRatingBeyondEight] & movies[moviesVoting10k]
print(moviesRatingBeyondEight.sum(), movies.shape, "\n\n", movies[moviesRatingBeyondEight])
print

43 (1629, 18)

                           title_x     imdb_id  \
0        Uri: The Surgical Strike   tt8291224
11                      Gully Boy   tt2395469
37              Article 15 (film)  tt10324144
40                Super 30 (film)   tt7485048
143                       Tumbbad   tt8239946
146                     Andhadhun   tt8108198
325              Pink (2016 film)   tt5571734
354                 Dangal (film)   tt5074352
418                        Masaan   tt4635372
426          Drishyam (2015 film)   tt4430212
436                 Talvar (film)   tt4934950
469             Queen (2014 film)   tt3322420
536                 Haider (film)   tt3390572
566                   Ugly (film)   tt2882328
567                     PK (film)   tt2338151
589                  Vishwaroopam   tt2199711
612            Bhaag Milkha Bhaag   tt2356180
638                 Shahid (film)   tt2181831
668       Paan Singh Tomar (film)   tt1620933
669                       Kahaani   tt1821480
693            Gangs of Wasseypur   tt1954470
694   Gangs of Wasseypur – Part 2   tt1954470
709                        Barfi!   tt2082197
714              OMG – Oh My God!   tt2283748
778      Zindagi Na Milegi Dobara   tt1562872
869             Udaan (2010 film)   tt1639426
912                      3 Idiots   tt1187043
930                 Gulaal (film)   tt1261047
1058     Black Friday (2007 film)   tt0400234
1066               Chak De! India   tt0871510
1127             Taare Zameen Par   tt0986264
1180             Khosla Ka Ghosla   tt0466460
1183         Lage Raho Munna Bhai   tt0456144
1188           Omkara (2006 film)   tt0488414
1195              Rang De Basanti   tt0405508
1223            Black (2005 film)   tt0375611
1252                 Iqbal (film)   tt0453729
1384                       Swades   tt0367110
1403          Munna Bhai M.B.B.S.   tt0374887
1554   The Legend of Bhagat Singh   tt0319736
1567                       Lagaan   tt0169102
1568                       Lagaan   tt0169102
1571               Dil Chahta Hai   tt0292490

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
11    https://upload.wikimedia.org/wikipedia/en/thum...
37    https://upload.wikimedia.org/wikipedia/en/thum...
40    https://upload.wikimedia.org/wikipedia/en/thum...
143   https://upload.wikimedia.org/wikipedia/en/thum...
146   https://upload.wikimedia.org/wikipedia/en/thum...
325   https://upload.wikimedia.org/wikipedia/en/thum...
354   https://upload.wikimedia.org/wikipedia/en/thum...
418   https://upload.wikimedia.org/wikipedia/en/thum...
426   https://upload.wikimedia.org/wikipedia/en/thum...
436   https://upload.wikimedia.org/wikipedia/en/thum...
469   https://upload.wikimedia.org/wikipedia/en/thum...
536   https://upload.wikimedia.org/wikipedia/en/thum...
566   https://upload.wikimedia.org/wikipedia/en/thum...
567   https://upload.wikimedia.org/wikipedia/en/thum...
589   https://upload.wikimedia.org/wikipedia/en/thum...
612   https://upload.wikimedia.org/wikipedia/en/thum...
638   https://upload.wikimedia.org/wikipedia/en/thum...
668   https://upload.wikimedia.org/wikipedia/en/thum...
669   https://upload.wikimedia.org/wikipedia/en/thum...
693   https://upload.wikimedia.org/wikipedia/en/thum...
694   https://upload.wikimedia.org/wikipedia/en/thum...
709   https://upload.wikimedia.org/wikipedia/en/thum...
714   https://upload.wikimedia.org/wikipedia/en/thum...
778   https://upload.wikimedia.org/wikipedia/en/thum...
869   https://upload.wikimedia.org/wikipedia/en/thum...
912   https://upload.wikimedia.org/wikipedia/en/thum...
930   https://upload.wikimedia.org/wikipedia/en/thum...
1058  https://upload.wikimedia.org/wikipedia/en/5/58...
1066  https://upload.wikimedia.org/wikipedia/en/thum...
1127  https://upload.wikimedia.org/wikipedia/en/thum...
1180  https://upload.wikimedia.org/wikipedia/en/thum...
1183  https://upload.wikimedia.org/wikipedia/en/thum...
1188  https://upload.wikimedia.org/wikipedia/en/thum...
1195  https://upload.wikimedia.org/wikipedia/en/thum...
1223  https://upload.wikimedia.org/wikipedia/en/thum...
1252  https://upload.wikimedia.org/wikipedia/en/thum...
1384  https://upload.wikimedia.org/wikipedia/en/8/85...
1403  https://upload.wikimedia.org/wikipedia/en/thum...
1554  https://upload.wikimedia.org/wikipedia/en/thum...
1567  https://upload.wikimedia.org/wikipedia/en/thum...
1568  https://upload.wikimedia.org/wikipedia/en/thum...
1571  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...
11              https://en.wikipedia.org/wiki/Gully_Boy
37      https://en.wikipedia.org/wiki/Article_15_(film)
40        https://en.wikipedia.org/wiki/Super_30_(film)
143               https://en.wikipedia.org/wiki/Tumbbad
146             https://en.wikipedia.org/wiki/Andhadhun
325      https://en.wikipedia.org/wiki/Pink_(2016_film)
354         https://en.wikipedia.org/wiki/Dangal_(film)
418         https://en.wikipedia.org/wiki/Fly_Away_Solo
426        https://en.wikipedia.org/wiki/Drishyam(2015)
436         https://en.wikipedia.org/wiki/Talvar_(film)
469     https://en.wikipedia.org/wiki/Queen_(2014_film)
536         https://en.wikipedia.org/wiki/Haider_(film)
566           https://en.wikipedia.org/wiki/Ugly_(film)
567             https://en.wikipedia.org/wiki/PK_(film)
589   https://en.wikipedia.org/wiki/Vishwaroop_(Hind...
612    https://en.wikipedia.org/wiki/Bhaag_Milkha_Bhaag
638         https://en.wikipedia.org/wiki/Shahid_(film)
668   https://en.wikipedia.org/wiki/Paan_Singh_Tomar...
669               https://en.wikipedia.org/wiki/Kahaani
693    https://en.wikipedia.org/wiki/Gangs_of_Wasseypur
694   https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...
709                https://en.wikipedia.org/wiki/Barfi!
714   https://en.wikipedia.org/wiki/Oh_My_God_(2012_...
778   https://en.wikipedia.org/wiki/Zindagi_Na_Mileg...
869     https://en.wikipedia.org/wiki/Udaan_(2010_film)
912              https://en.wikipedia.org/wiki/3_Idiots
930         https://en.wikipedia.org/wiki/Gulaal_(film)
1058  https://en.wikipedia.org/wiki/Black_Friday_(20...
1066       https://en.wikipedia.org/wiki/Chak_De!_India
1127     https://en.wikipedia.org/wiki/Taare_Zameen_Par
1180     https://en.wikipedia.org/wiki/Khosla_Ka_Ghosla
1183  https://en.wikipedia.org/wiki/Lage_Raho_Munna_...
1188   https://en.wikipedia.org/wiki/Omkara_(2006_film)
1195      https://en.wikipedia.org/wiki/Rang_De_Basanti
1223    https://en.wikipedia.org/wiki/Black_(2005_film)
1252         https://en.wikipedia.org/wiki/Iqbal_(film)
1384               https://en.wikipedia.org/wiki/Swades
1403  https://en.wikipedia.org/wiki/Munna_Bhai_M.B.B.S.
1554  https://en.wikipedia.org/wiki/The_Legend_of_Bh...
1567               https://en.wikipedia.org/wiki/Lagaan
1568  https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...
1571       https://en.wikipedia.org/wiki/Dil_Chahta_Hai

                                title_y                     original_title  \
0              Uri: The Surgical Strike           Uri: The Surgical Strike
11                            Gully Boy                          Gully Boy
37                           Article 15                         Article 15
40                             Super 30                           Super 30
143                             Tumbbad                            Tumbbad
146                           Andhadhun                          Andhadhun
325                                Pink                               Pink
354                              Dangal                             Dangal
418                              Masaan                             Masaan
426                            Drishyam                           Drishyam
436                              Talvar                             Talvar
469                               Queen                              Queen
536                              Haider                             Haider
566                                Ugly                               Ugly
567                                  PK                                 PK
589                        Vishwaroopam                       Vishwaroopam
612                  Bhaag Milkha Bhaag                 Bhaag Milkha Bhaag
638                              Shahid                             Shahid
668                    Paan Singh Tomar                   Paan Singh Tomar
669                             Kahaani                            Kahaani
693                  Gangs of Wasseypur                 Gangs of Wasseypur
694                  Gangs of Wasseypur                 Gangs of Wasseypur
709                              Barfi!                             Barfi!
714                     OMG: Oh My God!                    OMG: Oh My God!
778            Zindagi Na Milegi Dobara           Zindagi Na Milegi Dobara
869                               Udaan                              Udaan
912                            3 Idiots                           3 Idiots
930                              Gulaal                             Gulaal
1058                       Black Friday                       Black Friday
1066                     Chak de! India                     Chak De! India
1127                Like Stars on Earth                   Taare Zameen Par
1180                  Khosla Ka Ghosla!                  Khosla Ka Ghosla!
1183                Carry On Munna Bhai               Lage Raho Munna Bhai
1188                             Omkara                             Omkara
1195                    Rang De Basanti                    Rang De Basanti
1223                              Black                              Black
1252                              Iqbal                              Iqbal
1384                             Swades              Swades: We the People
1403                Munna Bhai M.B.B.S.                Munna Bhai M.B.B.S.
1554         The Legend of Bhagat Singh         The Legend of Bhagat Singh
1567  Lagaan: Once Upon a Time in India  Lagaan: Once Upon a Time in India
1568  Lagaan: Once Upon a Time in India  Lagaan: Once Upon a Time in India
1571                     Dil Chahta Hai                     Dil Chahta Hai

      is_adult  year_of_release runtime                   genres  imdb_rating  \
0            0             2019     138         Action|Drama|War          8.4
11           0             2019     153              Drama|Music          8.2
37           0             2019     130              Crime|Drama          8.3
40           0             2019     154          Biography|Drama          8.2
143          0             2018     104     Drama|Fantasy|Horror          8.2
146          0             2018     139           Crime|Thriller          8.4
325          0             2016     136           Drama|Thriller          8.2
354          0             2016     161   Action|Biography|Drama          8.4
418          0             2015     109                    Drama          8.1
426          0             2015     163      Crime|Drama|Mystery          8.2
436          0             2015     132      Crime|Drama|Mystery          8.2
469          0             2013     146             Comedy|Drama          8.2
536          0             2014     160       Action|Crime|Drama          8.1
566          0             2013     128      Crime|Drama|Mystery          8.1
567          0             2014     153     Comedy|Drama|Fantasy          8.1
589          0             2013     148          Action|Thriller          8.2
612          0             2013     186    Biography|Drama|Sport          8.2
638          0             2012     129    Biography|Crime|Drama          8.3
668          0             2012     135   Action|Biography|Crime          8.2
669          0             2012     122         Mystery|Thriller          8.1
693          0             2012     321      Action|Comedy|Crime          8.2
694          0             2012     321      Action|Comedy|Crime          8.2
709          0             2012     151     Comedy|Drama|Romance          8.1
714          0             2012     125     Comedy|Drama|Fantasy          8.2
778          0             2011     155             Comedy|Drama          8.1
869          0             2010     134                    Drama          8.2
912          0             2009     170             Comedy|Drama          8.4
930          0             2009     140     Crime|Drama|Thriller          8.1
1058         0             2004     143       Action|Crime|Drama          8.5
1066         0             2007     153       Drama|Family|Sport          8.2
1127         0             2007     165             Drama|Family          8.4
1180         0             2006     135       Comedy|Crime|Drama          8.3
1183         0             2006     144     Comedy|Drama|Romance          8.1
1188         0             2006     155       Action|Crime|Drama          8.1
1195         0             2006     167             Comedy|Drama          8.2
1223         0             2005     122                    Drama          8.2
1252         0             2005     132              Drama|Sport          8.1
1384         0             2004     210                    Drama          8.2
1403         0             2003     156     Comedy|Drama|Musical          8.1
1554         0             2002     155   Action|Biography|Drama          8.1
1567         0             2001     224  Adventure|Drama|Musical          8.1
1568         0             2001     224  Adventure|Drama|Musical          8.1
1571         0             2001     183     Comedy|Drama|Romance          8.1

      imdb_votes                                              story  \
0          35112  Divided over five chapters  the film chronicle...
11         22440  Gully Boy is a film about a 22-year-old boy "M...
37         13417  In the rural heartlands of India  an upright p...
40         13972  Anand Kumar  a Mathematics genius from a modes...
143        16535  Set in Tumbbad in the 1920s  the story revolve...
146        51615  Akash a blind pianist is preparing for a Londo...
325        33902  Deepak is a lawyer suffering from bipolar diso...
354       131338  Biopic of Mahavir Singh Phogat  who taught wre...
418        19904  Four lives intersect along the Ganges: a low c...
426        58340  Vijay Salgaonkar runs a cable TV network in a ...
436        26612  The story revolves around the mysterious murde...
469        56406  Queen is a movie about growing up. Rani (Kanga...
536        46912  Vishal Bhardwaj's adaptation of William Shakes...
566        17483  The film portrays the kidnapping of a little g...
567       143605  P. K. is a comedy of ideas about a stranger in...
589        38016  Vishwanathan  a Kathak dance teacher in New Yo...
612        56205  The true story of the "Flying Sikh" - world ch...
638        13537  Shahid traces the true story of slain human ri...
668        29994  Paan Singh Tomar is a Hindi-language film  bas...
669        53181  Kolkata is abuzz with the preparations for the...
693        71636  Shahid Khan is exiled after impersonating the ...
694        71636  Shahid Khan is exiled after impersonating the ...
709        70443  Set in the 1970s in a pretty corner of India  ...
714        46072  Kanji Lalji Mehta  though an atheist  owns a s...
778        60826  Three friends decide to turn their fantasy vac...
869        39567  After being abandoned for eight straight years...
912       310481  Farhan Qureshi and Raju Rastogi want to re-uni...
930        12799  Bikaner-based 28-year-old Dilip Kumar Singh is...
1058       16761  A dramatic presentation of the bomb blasts tha...
1066       68421  Kabir Khan (Shahrukh Khan) knows what it's lik...
1127      148498  Ishaan Awasthi is an eight-year-old child whos...
1180       20538  K.K. Khosla (Anupam Kher) is a middle class ma...
1183       39486  A hilarious underworld gangster known as Munna...
1188       17594  Advocate Raghunath Mishra has arranged the mar...
1195      103071  Sue comes to India to make a film on Indian re...
1223       31658  Based in Simla  the McNallys are an Anglo-Indi...
1252       14864  India - a Nation obsessed with cricket - and i...
1384       76737  Set in modern day India  Swades is a film that...
1403       67148  In India gangsters are called Bhai (brothers)....
1554       13455  Bhagat was born in British India during the ye...
1567       95686  This is the story about the resilience shown b...
1568       95686  This is the story about the resilience shown b...
1571       62313  Three young men Akash  Sameer  and Siddharth a...

                                                summary  \
0     Indian army special forces execute a covert op...
11    A coming-of-age story based on the lives of st...
37    In the rural heartlands of India  an upright p...
40    Based on life of Patna-based mathematician Ana...
143   A mythological story about a goddess who creat...
146   A series of mysterious events changes the life...
325   When three young women are implicated in a cri...
354   Former wrestler Mahavir Singh Phogat and his t...
418   Four lives intersect along the Ganges: a low c...
426   Desperate measures are taken by a man who trie...
436   An experienced investigator confronts several ...
469   A Delhi girl from a traditional family sets ou...
536   A young man returns to Kashmir after his fathe...
566   The case of a missing girl takes us through a ...
567   An alien on Earth loses the only device he can...
589   When a classical dancer's suspecting wife sets...
612   The truth behind the ascension of Milkha Singh...
638   The account of Human Rights lawyer Shahid Azmi...
668   The story of Paan Singh Tomar  an Indian athle...
669   A pregnant woman's search for her missing husb...
693   A clash between Sultan and Shahid Khan leads t...
694   A clash between Sultan and Shahid Khan leads t...
709   Three young people learn that love can neither...
714   A shopkeeper takes God to court when his shop ...
778   Three friends decide to turn their fantasy vac...
869   Expelled from his school  a 16-year old boy re...
912   Two friends are searching for their long lost ...
930   A law student witnesses deception  homicide  a...
1058  Black Friday is a film about the investigation...
1066  Kabir Khan is the coach of the Indian Women's ...
1127  An eight-year-old boy is thought to be a lazy ...
1180  A Delhi based retired middle class man tries h...
1183  Munna Bhai embarks on a journey with Mahatma G...
1188  A politically-minded enforcer's misguided trus...
1195  The story of six young Indians who assist an E...
1223  The cathartic tale of a young woman who can't ...
1252  Iqbal  the deaf and mute son of a farmer  has ...
1384  A successful Indian scientist returns to an In...
1403  A gangster sets out to fulfill his father's dr...
1554  The story of a young revolutionary who raised ...
1567  The people of a small village in Victorian Ind...
1568  The people of a small village in Victorian Ind...
1571  Three inseparable childhood friends are just o...

                                                tagline  \
0                                                   NaN
11                                    Apna Time Aayega!
37               Farq Bahut Kar Liya| Ab Farq Laayenge.
40    Inspired by the Life of Anand Kumar & His Stud...
143                                                 NaN
146                                                 NaN
325                                                 NaN
354       You think our girls are any lesser than boys?
418      Paths of grieve intersect on the Ganges River.
426                         Remake of a Malayalam movie
436                                                 NaN
469            Everything in life happens for the good.
536                                                 NaN

In [ ]:
# Aciton Movies with rating higher than 7.5
# actionMovies = movies["genres"].str.contains("Action")

actionMovies = movies["genres"].str.split("|").apply(lambda x: "Action" in x)
moviesActionRating = (actionMovies) & (movies["imdb_rating"] > 7.5)
movies[moviesActionRating].shape[0]

33

In [ ]:
# movies with rating higher than 8 and votes>10000

In [ ]:
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Eden Gardens, Kolkata",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Eden Gardens, Kolkata",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
# write a function that can return the track record of 2 teams against each other

## 🎯 Practice Tasks

🟢 **Easy:** Filter `ipl` to show only the 'Final' matches.

🟡 **Medium:** Count how many Super Over finishes have occurred in `ipl`.

🔴 **Hard:** Filter `movies` to find Action movies with an `imdb_rating` > 7.5 using `.str.contains()`.

In [ ]:
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
# 1. Single Condition
finals = ipl[ipl['MatchNumber'] == 'Final']
print("--- IPL Finals ---")
print(finals[['Season', 'WinningTeam']])

# 2. Counting filtered rows
super_overs = ipl[ipl['SuperOver'] == 'Y'].shape[0]
print(f"\nSuper Over count: {super_overs}")

# 3. Multiple Conditions (&)
csk_kolkata = ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'CSK')]
print(f"\nCSK wins in Kolkata: {csk_kolkata.shape[0]}")

# 4. String Methods in Filtering
action_high_rated = movies[(movies['genres'].str.contains('Action')) & (movies['imdb_rating'] > 7.5)]
print("\n--- Action Movies > 7.5 Rating ---")
print(action_high_rated[['title_x', 'imdb_rating']])

--- IPL Finals ---
   Season WinningTeam
0    2023         CSK
2    2022          GT
4    2021         CSK
6    2008         CSK
7    2008         CSK

Super Over count: 2

CSK wins in Kolkata: 2

--- Action Movies > 7.5 Rating ---
Empty DataFrame
Columns: [title_x, imdb_rating]
Index: []

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 5)
# ==========================================
# 🟢 Easy
print(ipl[ipl['MatchNumber'] == 'Final'])

# 🟡 Medium
print(ipl[ipl['SuperOver'] == 'Y'].shape[0])

# 🔴 Hard
mask1 = movies['genres'].str.contains('Action')
mask2 = movies['imdb_rating'] > 7.5
print(movies[mask1 & mask2])

```
</details>

In [ ]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 5)
# ==========================================
# 🟢 Easy: Filter `ipl` to show only the 'Final' matches
# YOUR CODE HERE:


# 🟡 Medium: Count how many Super Over finishes have occurred in `ipl`
# YOUR CODE HERE:


# 🔴 Hard: Filter `movies` to find Action movies with an `imdb_rating` > 7.5
# YOUR CODE HERE:

# 📘 Module 6: Adding & Modifying Columns

DataFrames are mutable. You can add a completely new column with a constant value, or derive a new column by performing operations on existing columns.

## 💡 Mental Model
Adding a column is exactly like adding a new key-value pair to a dictionary. `df['new_col'] = ...`. If the right side is a single value, it broadcasts to all rows. If it's a Series, it aligns by index.

## 📊 Visual Diagram
```text
┌─────────┬──────┐      ┌─────────┬──────┬─────────┐
│ actors  │ ...  │  =>  │ actors  │ ...  │ lead    │
├─────────┼──────┤      ├─────────┼──────┼─────────┤
│ A|B     │ ...  │      │ A|B     │ ...  │ A       │
│ C|D     │ ...  │      │ C|D     │ ...  │ C       │
└─────────┴──────┘      └─────────┴──────┴─────────┘
                          (Split string, take 1st element)
```

## 🌍 Real-World Use Case
Extracting the "Lead Actor" from a column formatted as `"Actor 1|Actor 2"` by splitting the string and taking the first element.

## ⚠️ Common Mistakes
Using `df.column_name = values` to add a new column. This creates an *attribute*, not a column! Always use bracket notation: `df['column_name'] = values`.

## 🎤 Interview Questions
**Q: How do you extract the first element of a pipe-separated string in a Pandas column?**
> **A:** Use `.str.split('|').apply(lambda x: x[0])` or `.str.split('|').str[0]`.

In [ ]:
students.head(3)

                      name  partner
student_id
1            Kailash Harjo       23
2              Esha Butala        1
3           Parveen Bhalla        3

In [ ]:
students["Univesity"] = "IIT Madras"
students.head()

                      name  partner   Univesity
student_id
1            Kailash Harjo       23  IIT Madras
2              Esha Butala        1  IIT Madras
3           Parveen Bhalla        3  IIT Madras
4              Marlo Dugal       14  IIT Madras
5              Kusum Bahri        6  IIT Madras

In [ ]:
print(students.columns.tolist(), students.head(), sep="\n\n")
students.rename(columns={"name": "full_name"}, inplace=True)
print(students.columns.tolist(), students.head(), sep="\n\n")
students.columns.values[0] = 'full_name'

students.head()

['name', 'partner', 'Univesity']

                      name  partner   Univesity
student_id
1            Kailash Harjo       23  IIT Madras
2              Esha Butala        1  IIT Madras
3           Parveen Bhalla        3  IIT Madras
4              Marlo Dugal       14  IIT Madras
5              Kusum Bahri        6  IIT Madras
['full_name', 'partner', 'Univesity']

                 full_name  partner   Univesity
student_id
1            Kailash Harjo       23  IIT Madras
2              Esha Butala        1  IIT Madras
3           Parveen Bhalla        3  IIT Madras
4              Marlo Dugal       14  IIT Madras
5              Kusum Bahri        6  IIT Madras

                 full_name  partner   Univesity first_name
student_id
1            Kailash Harjo       23  IIT Madras    Kailash
2              Esha Butala        1  IIT Madras       Esha
3           Parveen Bhalla        3  IIT Madras    Parveen
4              Marlo Dugal       14  IIT Madras      Marlo
5              Kusum Bahri        6  IIT Madras      Kusum

In [398]:
# make first_name as first column

# Create a mapping of column order

## 🎯 Practice Tasks

🟢 **Easy:** Add a new column `Country` to `movies` with the constant value `'India'`.

🟡 **Medium:** Create a new column `total_runs` in a mock DataFrame by adding two existing columns.

🔴 **Hard:** Extract the lead actor from the `actors` column in `movies` into a new column `lead_actor`.

In [ ]:
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
# 1. Adding a constant column
movies['Country'] = 'India'
print("--- Added Constant Column ---")
print(movies[['title_x', 'Country']].head(2))

# 2. Deriving from existing columns (String manipulation)
# Split by '|', then apply a lambda to get the first element (index 0)
movies['lead actor'] = movies['actors'].str.split('|').apply(lambda x: x[0])
print("\n--- Extracted Lead Actor ---")
print(movies[['title_x', 'actors', 'lead actor']].head(3))

--- Added Constant Column ---
    title_x Country
0  3 Idiots   India
1    Dangal   India

--- Extracted Lead Actor ---
    title_x                         actors  lead actor
0  3 Idiots      Aamir Khan|Kareena Kapoor  Aamir Khan
1    Dangal  Aamir Khan|Fatima Sana Shaikh  Aamir Khan
2        PK      Aamir Khan|Anushka Sharma  Aamir Khan

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 6)
# ==========================================
# 🟢 Easy
movies['Country'] = 'India'
print(movies['Country'].head())

# 🟡 Medium
df = pd.DataFrame({'A': [10, 20], 'B': [5, 15]})
df['total_runs'] = df['A'] + df['B']
print(df)

# 🔴 Hard
movies['lead_actor'] = movies['actors'].str.split('|').apply(lambda x: x[0])
print(movies[['title_x', 'lead_actor']].head())

```
</details>

In [ ]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 6)
# ==========================================
# 🟢 Easy: Add a new column `Country` to `movies` with the constant value `'India'`
# YOUR CODE HERE:


# 🟡 Medium: Create a new column `total_runs` in a mock DataFrame by adding two existing columns
# YOUR CODE HERE:


# 🔴 Hard: Extract the lead actor from the `actors` column in `movies` into a new column `lead_actor`
# YOUR CODE HERE:

# 📘 Module 7: Important Functions (`astype`, `value_counts`, `sort_values`)

- **`astype()`**: Converts a column to a different data type.
- **`value_counts()`**: Returns the frequency of unique values in a Series.
- **`sort_values()`**: Sorts the DataFrame by one or more columns.

## 💡 Mental Model
- `astype` changes the **lens** through which Pandas sees the data (e.g., treating numbers as text).
- `value_counts` is a **tally counter** for categorical data.
- `sort_values` is a **deck of cards** being organized by rank or suit.

## 📊 Visual Diagram
```text
['1', '2', '3'] -> astype(int) -> [1, 2, 3]

['A', 'B', 'A'] -> value_counts() -> A: 2, B: 1

[3, 1, 2] -> sort_values() -> [1, 2, 3]
```

## 🌍 Real-World Use Case
Using `value_counts()` to find which player won the most "Player of the Match" awards. Using `sort_values()` to rank movies by `imdb_rating` descending, and then by `year_of_release` ascending.

## ⚠️ Common Mistakes
Forgetting that `astype()` returns a *new* Series. You must assign it back: `df['col'] = df['col'].astype(int)`. Also, forgetting `ascending=False` when you want the highest values at the top.

## 🎤 Interview Questions
**Q: How do you sort a DataFrame by multiple columns with different ascending/descending orders?**
> **A:** Pass lists to the parameters: `df.sort_values(by=['col1', 'col2'], ascending=[True, False])`.

In [399]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [404]:
ipl['Season'] = ipl['Season'].astype("category")
ipl["Team1"] = ipl["Team1"].astype("category")
ipl["Team2"] = ipl["Team2"].astype("category")
ipl.info() # check the deduction in memory usage

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    category
 6   Team2            950 non-null    category
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: category(3), float64(1), int64(1), str(15)
memory usage: 129.5 KB

## 🎯 Practice Tasks

🟢 **Easy:** Find the frequency of each `City` in the `ipl` DataFrame using `value_counts()`.

🟡 **Medium:** Sort the `movies` DataFrame by `imdb_rating` in descending order.

🔴 **Hard:** Convert the `year_of_release` column in `movies` to a string type using `astype()`.

In [ ]:
# ==========================================
# 💻 CODE EXAMPLE & EXPLANATION
# ==========================================
# 1. value_counts
print("--- City Frequencies ---")
print(ipl['City'].value_counts())

# 2. sort_values
print("\n--- Movies Sorted by Rating (Desc) ---")
print(movies.sort_values(by='imdb_rating', ascending=False)[['title_x', 'imdb_rating']])

# 3. astype
print("\n--- Data Type Conversion ---")
print(f"Before: {movies['year_of_release'].dtype}")
movies['year_of_release'] = movies['year_of_release'].astype(str)
print(f"After: {movies['year_of_release'].dtype}")

--- City Frequencies ---
City
Ahmedabad    4
Kolkata      3
Delhi        1
Name: count, dtype: int64

--- Movies Sorted by Rating (Desc) ---
             title_x  imdb_rating
0           3 Idiots          8.4
1             Dangal          8.3
2                 PK          8.1
5  Bajrangi Bhaijaan          8.0
6              Sanju          7.9
7   Secret Superstar          7.8
4              Jawan          6.8
3            Pathaan          6.5

--- Data Type Conversion ---
Before: int64
After: str

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ SOLUTIONS (Module 7)
# ==========================================
# 🟢 Easy
print(ipl['City'].value_counts())

# 🟡 Medium
print(movies.sort_values(by='imdb_rating', ascending=False))

# 🔴 Hard
movies['year_of_release'] = movies['year_of_release'].astype(str)
print(movies['year_of_release'].dtype)

```
</details>

In [ ]:
# ==========================================
# 🎯 YOUR TURN: PRACTICE TASKS (Module 7)
# ==========================================
# 🟢 Easy: Find the frequency of each `City` in the `ipl` DataFrame using `value_counts()`
# YOUR CODE HERE:


# 🟡 Medium: Sort the `movies` DataFrame by `imdb_rating` in descending order
# YOUR CODE HERE:


# 🔴 Hard: Convert the `year_of_release` column in `movies` to a string type using `astype()`
# YOUR CODE HERE:

# 🎉 Congratulations!
You have completed the **Pandas DataFrames Masterclass**.