# 🐼 Pandas Part 4: GroupBy Mastery Notebook
**From Split-Apply-Combine to Advanced Feature Engineering**

Welcome to Part 4! GroupBy is the **heart of Data Analysis**. It is the Pandas equivalent of SQL's `GROUP BY`, Excel's Pivot Tables, and the foundation of Feature Engineering in Machine Learning.

Every concept in this notebook follows the **16-Step Mastery Framework**:

`Theory → Mental Model → Diagram → Syntax → Example → Output → Explanation → Mistakes → Interview → Practice (Levels 1-5) → SQL → DS Use Case → Mini Challenge`

We will use **3 Industry Datasets**: 
1. 🎬 **Movies** (Genres, Ratings, Revenue)
2. 🏏 **IPL** (Batsmen, Runs, Overs)
3. 🏢 **Employees** (Departments, Salaries)

In [ ]:
# ==========================================
# 🛠️ SETUP & INDUSTRY MOCK DATA
# ==========================================
import pandas as pd
import numpy as np

# 1. Mock Movies Data
movies = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\imdb-top-1000.csv")

# 2. Mock IPL Data
ipl_data = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\ipl-matches.csv")

# Students
students_data = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\students.csv")

# Deliveries Data

deliveries = pd.read_csv(r"D:\Projects\personalNotes\assets\pandas\deliveries.csv")

# 3. Employees Dataset
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'dept': ['HR', 'IT', 'IT', 'HR', 'Finance', 'IT'],
    'salary': [50000, 80000, 90000, 55000, 70000, 85000],
    'age': [25, 30, 35, 28, 40, 32],
    'experience': [2, 5, 8, 3, 12, 6]
})

# 📘 Module 1: The Split-Apply-Combine Paradigm

## 🧠  Theory
The `groupby()` operation involves three main steps:
1. **Splitting**: Dividing the data into groups based on some criteria.
2. **Applying**: Applying a function to each group independently.
3. **Combining**: Combining the results into a new data structure.

## 💡  Mental Model
Think of a **Deck of Cards**. 
- **Split**: Sort the deck into 4 piles (Hearts, Diamonds, Clubs, Spades).
- **Apply**: Count the number of face cards in *each* pile.
- **Combine**: Write down the 4 counts on a piece of paper.

## 📊  Visual Diagram
```mermaid
flowchart TD
    A[Original DataFrame] --> B[Split by 'Genre']
    B --> C[Action Group]
    B --> D[Comedy Group]
    C --> E[Apply: Mean Rating]
    D --> F[Apply: Mean Rating]
    E --> G[Combine Results]
    F --> G
```

## 🛠️ Syntax
```python
df.groupby('column_name')['target_column'].aggregation_function()
```

## 💻 Example 
```python
# Find the genre with highest avg IMDB rating
avg_ratings = movies.groupby('genre')['imdb_rating'].mean()
```
**Output:**
```text
genre
Action    8.500000
Comedy    7.650000
Sci-Fi    8.150000
Name: imdb_rating, dtype: float64
```
**Explanation:** 
1. `groupby('genre')` splits the DataFrame into 3 separate chunks.
2. `['imdb_rating']` selects only the rating column from those chunks.
3. `.mean()` calculates the average for each chunk and combines them into a Series.

## ⚠️ Common Mistakes & Debugging
**Mistake 1: The Lazy Object Trap**
```python
movies.groupby('genre') # Returns a DataFrameGroupBy object, NOT the result!
```
**Mistake 2: Missing Quotes**
```python
movies.groupby(genre) # ❌ NameError: name 'genre' is not defined
```
**🐛 Debugging Task:** Fix this code: `df.groupby(city)['salary'].mean()`
*(Answer: Add quotes around 'city' -> `df.groupby('city')['salary'].mean()`)*

## 🎤  Interview Questions & Output Prediction
**Q1: What is the difference between `size()` and `count()` in GroupBy?**
> **A:** `size()` counts the number of rows in each group (including NaNs). `count()` counts the number of *non-null* values in a specific column.

**🔮 Output Prediction:**
```python
df = pd.DataFrame({'A': ['X', 'X', 'Y'], 'B': [1, np.nan, 3]})
print(df.groupby('A')['B'].size())
print(df.groupby('A')['B'].count())
```
**Answer:** `size()` returns `X: 2, Y: 1`. `count()` returns `X: 1, Y: 1` (ignores the NaN in X).

In [4]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [5]:
genres = movies.groupby("Genre")
print(genres)

<pandas.api.typing.DataFrameGroupBy object at 0x000001899A3FBFE0>

In [6]:
# Applying built in aggregation functions on groupby objects
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [7]:
# find the top 3 genres by total earning
movies.groupby("Genre").sum()["Gross"].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [8]:
# Alternate approach: # find the top 3 genres by total earning
# Better approach but why?
movies.groupby("Genre")["Gross"].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [9]:
# find the genre with highest avg IMDB rating
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False).head(3)

Genre
Western    8.350000
Crime      8.016822
Fantasy    8.000000
Name: IMDB_Rating, dtype: float64

In [10]:
# find director with most popularity

movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending=False).head()

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
Name: No_of_Votes, dtype: int64

In [11]:
# find the highest rated movie of each genre
movies.groupby("Genre")["IMDB_Rating"].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [12]:
# find number of movies done by each actor
# movies.groupby("Star1").value_counts()
movies.groupby("Star1")["Series_Title"].value_counts().sort_values(ascending=False)

Star1                 Series_Title
Aamir Khan            Andaz Apna Apna          1
                      Dangal                   1
                      3 Idiots                 1
                      Dil Chahta Hai           1
                      Rang De Basanti          1
                                              ..
Zbigniew Zamachowski  Trois couleurs: Blanc    1
Zooey Deschanel       (500) Days of Summer     1
Çetin Tekindor        Babam ve Oglum           1
Éric Toledano         The Intouchables         1
Ömer Faruk Sorak      Vizontele                1
Name: count, Length: 1000, dtype: int64

## Groupby Attributes and Methods

In [ ]:
# find total numbers of groups in movies for genre column
len(movies.groupby("Genre"))

14

In [26]:
movies["Genre"].nunique()

14

In [21]:
# find items in each group
movies.groupby("Genre").size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [27]:
movies["Genre"].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [ ]:
# first () / Last() 
movies.groupby("Genre").first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [29]:
movies.groupby("Genre").last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [30]:
movies.groupby("Genre").nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [ ]:
# Get Group - to fetch a particular group
movies.groupby("Genre").get_group("Fantasy")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [33]:
movies[movies["Genre"] == "Fantasy"]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [35]:
print(movies.groupby("Genre").groups)

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [40]:
genres = movies.groupby("Genre")
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [41]:
genres.sample()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
893,Sicario,2015,121,Action,7.6,Denis Villeneuve,Emily Blunt,371291,46889293.0,82.0
402,Dances with Wolves,1990,181,Adventure,8.0,Kevin Costner,Kevin Costner,240266,184208848.0,72.0
358,Persepolis,2007,96,Animation,8.0,Vincent Paronnaud,Marjane Satrapi,88656,4445756.0,90.0
579,M.S. Dhoni: The Untold Story,2016,184,Biography,7.8,Neeraj Pandey,Sushant Singh Rajput,40416,1782795.0,NaN
455,Arsenic and Old Lace,1942,118,Comedy,8.0,Frank Capra,Cary Grant,65101,460853100.0,NaN
287,Le samouraï,1967,105,Crime,8.1,Jean-Pierre Melville,Alain Delon,45434,39481.0,NaN
295,The Man Who Shot Liberty Valance,1962,123,Drama,8.1,John Ford,James Stewart,68827,541426567.0,94.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
961,Lost Highway,1997,134,Mystery,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [42]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

## 🎯 Practice Tasks

**Level 1 (Easy):** Find the total `revenue_mil` for each `genre` in the `movies` DataFrame.

**Level 2 (Medium):** Find the highest rated movie *per genre* (Return the title and rating).

**Level 3 (Hard):** Find the `director` with the most popularity (defined as the highest total sum of `revenue_mil`).

## 🏏  Real Dataset Practice
**IPL:** Find the **top 10 batsman** in terms of total `runs`.

## 🗄️  SQL Equivalent
```sql
SELECT genre, AVG(imdb_rating) 
FROM movies 
GROUP BY genre;
```

## 🤖  Data Science Use Case
**Customer Segmentation:** Calculating the average spending per customer segment to identify high-value targets for marketing campaigns.

## 🏆  Mini Challenge
Calculate the average salary department-wise **without** using the `groupby()` function. *(Hint: Use boolean masking and a loop or dictionary!)*

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ MODULE 1: SOLUTIONS
# ==========================================
# Level 1
print(movies.groupby('genre')['revenue_mil'].sum())

# Level 2
idx = movies.groupby('genre')['imdb_rating'].idxmax()
print(movies.loc[idx][['title', 'genre', 'imdb_rating']])

# Level 3
print(movies.groupby('director')['revenue_mil'].sum().idxmax())

# Real Dataset
print(ipl.groupby('batsman')['runs'].sum().sort_values(ascending=False).head(10))

# Mini Challenge
depts = employees['dept'].unique()
for d in depts:
    mask = employees['dept'] == d
    print(f"{d}: {employees[mask]['salary'].mean()}")
    
```
</details>

In [14]:
# ==========================================
# 💻 MODULE 1: PRACTICE AREA
# ==========================================
# Level 1: Total revenue by genre
# YOUR CODE HERE:

# Level 2: Highest rated movie per genre
# YOUR CODE HERE:

# Level 3: Director with most popularity
# YOUR CODE HERE:

# Real Dataset: Top 10 batsman by runs
# YOUR CODE HERE:

# Mini Challenge: Avg salary by dept WITHOUT groupby()
# YOUR CODE HERE:

# 📘 Module 2: The `agg()` Masterclass

## 🧠 1. Theory
`groupby` creates an invisible object. You can inspect it using attributes like `size()`, `first()`, `last()`, and `get_group()`.
More importantly, the `agg()` method allows you to pass multiple aggregation functions, or apply different functions to different columns simultaneously using a dictionary.

## 💡 2. Mental Model
`*get_group('Action')` is like asking a librarian to hand you only the stack of Action movies.

Think of `agg()` as a **Multi-Tool**. Instead of asking "What is the sum?", then "What is the max?", you hand the DataFrame a list of questions and get all the answers at once.

## 📊 3. Visual Diagram
```text
DataFrame
   genre  rating  revenue
   Action 8.5     800
   Action 8.1     1000
   ↓ groupby('genre').agg({
       'rating': ['mean', 'max'],
       'revenue': 'sum'
   })
Result
        rating      revenue
        mean  max   sum
genre
Action  8.3   8.5   1800
```

## 🛠️ 4. Syntax
```python
# Dictionary approach
df.groupby('col').agg({'col1': ['mean', 'max'], 'col2': 'sum'})

# Named Aggregation approach (Cleaner)
df.groupby('col').agg(avg_col1=('col1', 'mean'), sum_col2=('col2', 'sum'))
```

## 💻 5. Example & 6. Output & 7. Explanation
```python
# Dictionary approach
result = movies.groupby('genre').agg({
    'imdb_rating': ['mean', 'max'],
    'revenue_mil': 'sum'
})
```
**Output:** Creates a DataFrame with a **MultiIndex** for columns.
**Explanation:** The dictionary maps each column to the specific functions you want to apply to it.

## ⚠️ 8. Common Mistakes & Debugging
**Mistake:** Forgetting that dictionary aggregation creates a MultiIndex column structure, which can be annoying to access later.
**🐛 Debugging Task:** How do you flatten the MultiIndex columns created by `agg()`?
*(Answer: Chain `.columns = ['_'.join(col) for col in cols]` or use Named Aggregation instead!)*

Using `get_group` carelessly: 
`movies.groupby('genre').get_group('Horror')` will throw a `KeyError` because 'Horror' doesn't exist in our mock data. Use boolean filtering `df[df['genre'] == 'Horror']` if you aren't sure a category exists.

## 🎤 9. Interview Questions & Output Prediction
**Q1: What is the difference between `agg()` and `apply()`?**
> **A:** `agg()` is optimized for reduction functions (turning a group into a scalar). It works column-by-column efficiently. `apply()` passes the entire sub-DataFrame to a custom function, allowing for row-dependent logic but suffering from a performance penalty.

**Q2: What is the difference between `size()` and `count()` in GroupBy?**
> **A:** `size()` counts the raw number of rows in each group (including NaNs). `count()` counts the number of non-null values in a specific column.

In [52]:
# agg method
# passing dict
movies.groupby("Genre").agg(
    {
        "Runtime": "mean",
        "IMDB_Rating": "mean",
        "No_of_Votes": "sum",
        "Gross": "sum",
        "Metascore": "min"

    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [57]:
# passing list

movies.groupby("Genre").agg(
    [
        "min", "max", "sum"
    ]
)

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                                             Released_Year  \
                                                         sum           min
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...          1924
Adventure  InterstellarBack to the FutureInglourious Bast...          1925
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...          1940
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...          1928
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...          1921
Crime      The GodfatherThe Godfather: Part II12 Angry Me...          1931
Drama      The Shawshank RedemptionFight ClubForrest Gump...          1925
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...          1971
Fantasy                Das Cabinet des Dr. CaligariNosferatu          1920
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt          1941
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...          1933
Mystery    MementoRear WindowVertigoShutter IslandKahaani...          1938
Thriller                                     Wait Until Dark          1967
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...          1965

                                                                   Runtime  \
            max                                                sum     min
Genre
Action     2019  2008200320102001200219991980197719621954200019...      45
Adventure    PG  2014198520091981196819621959201319751963194819...      88
Animation  2020  2001199419882016201820172008199719952019200920...      71
Biography  2020  1993199020202011200220171995198420182013201320...      93
Comedy     2020  2019199719361931200919641940200120001973196019...      68
Crime      2019  1972197419571994200219991995199120192006199519...      80
Drama      2020  1994199919941975202019981946201420061998198819...      64
Family     1982                                           19821971     100
Fantasy    1922                                           19201922      76
Film-Noir  1949                                       194919411943     100
Horror     2017       19601979198219731968196120171978193320042001      71
Mystery    2012   200019541958201020121995197219381988201219981997      96
Thriller   1967                                               1967     108
Western    1976                                   1966196819651976     132

                      IMDB_Rating  ...  \
           max    sum         min  ...
Genre                              ...
Action     321  22196         7.6  ...
Adventure  228   9656         7.6  ...
Animation  137   8166         7.6  ...
Biography  209  11970         7.6  ...
Comedy     188  17380         7.6  ...
Crime      229  13524         7.6  ...
Drama      242  36049         7.6  ...
Family     115    215         7.8  ...
Fantasy     94    170         7.9  ...
Film-Noir  108    312         7.8  ...
Horror     122   1123         7.6  ...
Mystery    138   1429         7.6  ...
Thriller   108    108         7.8  ...
Western    165    593         7.8  ...

                                                       Star1 No_of_Votes  \
                                                         sum         min
Genre
Action     Christian BaleElijah WoodLeonardo DiCaprioElij...       25312
Adventure  Matthew McConaugheyMichael J. FoxBrad PittJürg...       29999
Animation  Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...       25229
Biography  Liam NeesonRobert De NiroLin-Manuel MirandaÉri...       27254
Comedy     Kang-ho SongRoberto BenigniCharles ChaplinChar...       26337
Crime      Marlon BrandoAl PacinoHenry FondaJohn Travolta...       27712
Drama      Tim RobbinsBrad PittTom HanksJack NicholsonSur...       25088
Family                               Henry ThomasGene Wilder      178731
Fantasy                             Werner KraussMax Schreck       57428
Film-Noir           Orson WellesHumphrey BogartTeresa Wright       59556
Horror     Anthony PerkinsSigourney WeaverKurt RussellEll...       27007
Mystery    Guy PearceJames StewartJames StewartLeonardo D...       33982
Thriller                                      Audrey Hepburn       27733
Western    Clint EastwoodHenry FondaClint EastwoodClint E...       65659

                                    Gross                             \
               max       sum          min          max           sum
Genre
Action     2303232  72282412       3296.0  936662225.0  3.263226e+10
Adventure  1512360  22576163      61001.0  874211619.0  9.496922e+09
Animation   999790  21978630     128985.0  873839108.0  1.463147e+10
Biography  1213505  24006844      21877.0  753585104.0  8.276358e+09
Comedy      939631  27620327       1305.0  886752933.0  1.566387e+10
Crime      1826188  33533615       6013.0  790482117.0  8.452632e+09
Drama      2343110  61367304       3600.0  924558264.0  3.540997e+10
Family      372490    551221    4000000.0  435110554.0  4.391106e+08
Fantasy      88794    146222  337574718.0  445151978.0  7.827267e+08
Film-Noir   158731    367215     449191.0  123353292.0  1.259105e+08
Horror      787806   3742556      89029.0  298791505.0  1.034649e+09
Mystery    1129894   4203004    1035953.0  474203697.0  1.256417e+09
Thriller     27733     27733   17550741.0   17550741.0  1.755074e+07
Western     688390   1289665    5321508.0   31800000.0  5.822151e+07

          Metascore
                min    max      sum
Genre
Action         33.0   98.0  10499.0
Adventure      41.0  100.0   5020.0
Animation      61.0   96.0   6082.0
Biography      48.0   97.0   6023.0
Comedy         45.0   99.0   9840.0
Crime          47.0  100.0   6706.0
Drama          28.0  100.0  19208.0
Family         67.0   91.0    158.0
Fantasy         NaN    NaN      0.0
Film-Noir      94.0   97.0    287.0
Horror         46.0   97.0    880.0
Mystery        52.0  100.0    633.0
Thriller       81.0   81.0     81.0
Western        69.0   90.0    313.0

[14 rows x 27 columns]

In [60]:
# agg method
# passing dict
movies.groupby("Genre").agg(
    {
        "Runtime": ["mean", "max"],
        "IMDB_Rating": "mean",
        "No_of_Votes": "sum",
        "Gross": ["sum", "mean", "max"],
        "Metascore": "min"

    }
)

              Runtime      IMDB_Rating No_of_Votes         Gross  \
                 mean  max        mean         sum           sum
Genre
Action     129.046512  321    7.949419    72282412  3.263226e+10
Adventure  134.111111  228    7.937500    22576163  9.496922e+09
Animation   99.585366  137    7.930488    21978630  1.463147e+10
Biography  136.022727  209    7.938636    24006844  8.276358e+09
Comedy     112.129032  188    7.901290    27620327  1.566387e+10
Crime      126.392523  229    8.016822    33533615  8.452632e+09
Drama      124.737024  242    7.957439    61367304  3.540997e+10
Family     107.500000  115    7.800000      551221  4.391106e+08
Fantasy     85.000000   94    8.000000      146222  7.827267e+08
Film-Noir  104.000000  108    7.966667      367215  1.259105e+08
Horror     102.090909  122    7.909091     3742556  1.034649e+09
Mystery    119.083333  138    7.975000     4203004  1.256417e+09
Thriller   108.000000  108    7.800000       27733  1.755074e+07
Western    148.250000  165    8.350000     1289665  5.822151e+07

                                     Metascore
                   mean          max       min
Genre
Action     1.897224e+08  936662225.0      33.0
Adventure  1.319017e+08  874211619.0      41.0
Animation  1.784326e+08  873839108.0      61.0
Biography  9.404952e+07  753585104.0      48.0
Comedy     1.010572e+08  886752933.0      45.0
Crime      7.899656e+07  790482117.0      47.0
Drama      1.225259e+08  924558264.0      28.0
Family     2.195553e+08  435110554.0      67.0
Fantasy    3.913633e+08  445151978.0       NaN
Film-Noir  4.197018e+07  123353292.0      94.0
Horror     9.405902e+07  298791505.0      46.0
Mystery    1.047014e+08  474203697.0      52.0
Thriller   1.755074e+07   17550741.0      81.0
Western    1.455538e+07   31800000.0      69.0

In [69]:
import pandas as pd

# 1. Initialize an empty DataFrame
# We create a blank DataFrame that has the exact same column headers as our original 'movies' data.
# This acts as an empty container where we will collect our final results.
df = pd.DataFrame(columns=movies.columns)

# 2. Iterate through the grouped data
# 'genres' is a pandas GroupBy object. When looping over it, it yields two things per iteration:
# - 'group': The name of the group (e.g., 'Action', 'Comedy')
# - 'data': A DataFrame containing only the rows belonging to that specific group
for group, data in genres:
    
    # Find the highest number in the "IMDB_Rating" column for this specific genre
    max_rating = data["IMDB_Rating"].max()
    
    # 3. Filter and Concatenate
    # First, data[data["IMDB_Rating"] == max_rating] filters the current genre's data to keep 
    # only the row(s) where the rating equals the max rating we just found.
    # Next, pd.concat merges our main 'df' container with those newly filtered rows.
    # ignore_index=True resets the row numbers so they count up cleanly (0, 1, 2...) instead of 
    # keeping the original messy index numbers from the main dataset.
    df = pd.concat(
        [df, data[data["IMDB_Rating"] == max_rating]],
        ignore_index=True
    )

# 4. Display the final result
# Output the accumulated DataFrame containing the highest-rated movies per genre.
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
1,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
2,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
3,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
4,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
5,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
6,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
7,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
8,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
9,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
10,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
11,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
12,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
13,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
14,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
15,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
16,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

## 🎯 Practice Tasks
- **Level 1 (Easy):** Use `agg()` with a **list** to find the `min`, `max`, and `mean` of `imdb_rating` for each `genre`.
- **Level 2 (Medium):** Use `agg()` with a **dictionary** to find the `sum` of `revenue_mil` and the `mean` of `metascore` per `genre`.
- **Level 3 (Hard):** Use **Named Aggregation** to create a clean DataFrame with columns: `avg_rating`, `total_revenue`, and `movie_count`.

1. Use `get_group('Comedy')` to view only the Comedy movies as a DataFrame.
2. Use `agg()` with a list `['min', 'max', 'mean']` to find those stats for `imdb_rating` grouped by genre.
3. Use `agg()` with a dictionary to find the `sum` of `revenue_mil` AND the mean of `metascore` grouped by `genre`.

## 🏏 13. Real Dataset Practice
**IPL:** Group by `batsman` and find: `runs` -> sum, `balls` -> sum, and calculate the strike rate (`runs` / `balls` * 100) using a custom lambda in `agg()`.

## 🗄️ 14. SQL Equivalent
```sql
SELECT genre, 
       AVG(imdb_rating) as avg_rating, 
       MAX(imdb_rating) as max_rating,
       SUM(revenue_mil) as total_revenue
FROM movies 
GROUP BY genre;
```

## 🤖 15. Data Science Use Case
**Feature Engineering:** Creating multiple statistical features (mean, std, skew) of a target variable grouped by a categorical ID to feed into a Machine Learning model.

## 🏆 16. Mini Challenge
Write a custom lambda function inside `agg()` that calculates the **range** (max - min) of the `salary` column for each department.


<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ MODULE 2: SOLUTIONS
# ==========================================
# Level 1
print(movies.groupby('genre')['imdb_rating'].agg(['min', 'max', 'mean']))

# Level 2
print(movies.groupby('genre').agg({'revenue_mil': 'sum', 'metascore': 'mean'}))

# Level 3
print(movies.groupby('genre').agg(
    avg_rating=('imdb_rating', 'mean'),
    total_revenue=('revenue_mil', 'sum'),
    movie_count=('title', 'count')
))

# Real Dataset
print(ipl.groupby('batsman').agg(
    total_runs=('runs', 'sum'),
    total_balls=('balls', 'sum'),
    strike_rate=('runs', lambda x: x.sum() / ipl.loc[x.index, 'balls'].sum() * 100)
))
# Note: A simpler way for SR is to calculate it after aggregation!

# Mini Challenge
print(employees.groupby('dept')['salary'].agg(lambda x: x.max() - x.min()))

```

</details>

In [15]:
# ==========================================
# 💻 MODULE 2: PRACTICE AREA
# ==========================================
# Level 1: List agg
# YOUR CODE HERE:

# Level 2: Dict agg
# YOUR CODE HERE:

# Level 3: Named Aggregation
# YOUR CODE HERE:

# Real Dataset: IPL batsman stats with custom lambda
# YOUR CODE HERE:

# Mini Challenge: Range of salary per dept
# YOUR CODE HERE:

In [16]:
# --- EXAMPLE CODE ---
# Using agg with a dictionary
"""print("--- agg with Dictionary ---")
print(movies.groupby('genre').agg({
    'imdb_rating': 'mean',
    'revenue_mil': 'sum'
}))"""

# --- PRACTICE AREA ---
# Task 1: Use get_group to show only Comedy movies


# Task 2: Find min, max, mean of imdb_rating by genre


# Task 3: Find sum of revenue and mean of metascore by genre using a dictionary

'print("--- agg with Dictionary ---")\nprint(movies.groupby(\'genre\').agg({\n    \'imdb_rating\': \'mean\',\n    \'revenue_mil\': \'sum\'\n}))'

# 📘 Module 3: Advanced GroupBy `transform()` vs `apply()`

## 🧠 1. Theory
- **`transform()`**: Like `apply`, but **must return a Series of the same size as the group**. Used for broadcasting (e.g., subtracting the group mean from every row).
- **`apply()`**: The **Wild Card**. It can do anything, return anything, and is used for complex custom logic that changes the shape of the data.

## 💡 2. Mental Model
- **`agg`** crushes the group into a **single number** (Scalar).
- **`transform`** keeps the group's **original shape** but fills it with a calculated value (Broadcasting).
- **`apply`** is a **Factory Conveyor Belt**. It processes each group and can output a scalar, a Series, or a DataFrame.

**🌍 Real World Example**: "Find the normalized rating for every movie based on its genre." You can't use `agg` because you want to keep every movie row intact. You must use `transform` to calculate the genre's mean and subtract it from the specific movie's rating.

## 📊 3. Visual Diagram
```text
Group: [10, 20, 30] (Mean = 20)

transform(lambda x: x - x.mean())
→ [-10, 0, 10]  <-- Same shape! (Normalized)

apply(lambda x: x.max())
→ 30            <-- Crushed to scalar!
```

## 🛠️ 4. Syntax
```python
# Broadcasting a group statistic back to original rows
df['new_col'] = df.groupby('col')['target'].transform('mean')

# Applying complex custom logic
df.groupby('col').apply(custom_function)
```

## 💻 5. Example & 6. Output & 7. Explanation
```python
# Find normalized IMDB rating group wise (Z-Score)
movies['rating_normalized'] = movies.groupby('genre')['imdb_rating'] \
    .transform(lambda x: (x - x.mean()) / x.std())
```
**Output:** The original DataFrame gets a new column where every movie has its Z-score relative to its genre.
**Explanation:** `transform` calculates the mean and std for the genre, then broadcasts the Z-score calculation back to every row in that genre.

## ⚠️ 8. Common Mistakes & Debugging
**Mistake:** Using `apply` when `transform` is needed.
```python
# ❌ ValueError: Length mismatch
movies['rating_normalized'] = movies.groupby('genre')['imdb_rating'].apply(lambda x: x - x.mean())
```
**Explanation:** `apply` returns one value per group (e.g., 3 values for 3 genres). You can't assign 3 values to a DataFrame with 7 rows!

## 🎤 9. Interview Questions & Output Prediction
**Q1: Why is `groupby().apply()` slow?**
> **A:** Because it breaks Pandas' C-level vectorization. It forces Pandas to loop through the groups in pure Python. Always prefer built-in `agg()` or `transform()` methods if possible!

### Split-Apply-Combine

The **Split-Apply-Combine** strategy is a foundational concept in data analysis. It was popularized by Hadley Wickham (creator of many R data tools) and is the exact logic that powers the `.groupby()` function in pandas.

Think of it as a way to break a massive, complex dataset into smaller, manageable pieces, perform an operation on each piece independently, and then glue the results back together.

Here is exactly how the three steps work:

### 1. Split

You break the main dataset into smaller groups based on a specific key or condition.

* **Concept:** "Take all this data and separate it into buckets based on category X."
* **Pandas equivalent:** `df.groupby('Genre')`
* *In your movie dataset:* You took the massive list of movies and split them into separate "buckets" for Action, Comedy, Drama, etc.

### 2. Apply

You apply a specific function to each of those independent buckets one by one. The `Apply` step usually falls into one of three categories:

* **Aggregation:** Calculating a summary statistic for each group (e.g., finding the `sum()`, `mean()`, or `max()` rating per genre). This reduces the group to a single number.
* **Transformation:** Doing a calculation on the group that keeps the same number of rows (e.g., filling missing values using the average of *that specific group*).
* **Filtration:** Keeping or discarding entire groups based on a rule (e.g., only keeping genres that have more than 50 movies).
* *In your movie dataset:* You applied a function to count how many titles started with "A" inside each individual genre bucket.

### 3. Combine

You take the results from the "Apply" step and stitch them back together into a single, cohesive data structure (like a new DataFrame or Series).

* **Concept:** "Gather all the results from the buckets and put them into a neat table."
* **Pandas equivalent:** Pandas does this step for you automatically behind the scenes when you run a groupby operation!
* *In your movie dataset:* Pandas took the counts from the Action bucket, the Comedy bucket, and the Drama bucket, and combined them into a single Series where the index was the Genre and the value was the count.

---

### Why is this strategy so powerful?

Without this strategy, you would have to write messy `for` loops to iterate through all unique genres, filter the data, calculate the math, store the results in a dictionary, and manually convert it back to a table.

The **Split-Apply-Combine** strategy (via `.groupby()`) lets you do all of that in a single, highly-optimized line of code:

```python
movies.groupby('Genre')['IMDB_Rating'].mean()

```

In [ ]:
# find the number of movies starting with "A" for each genre

def beginWithA(group):
    # 1. group["Series_Title"]: Selects just the title column for the current genre group.
    # 2. .str.startswith("A"): Checks each title, returning True if it starts with 'A' and False if it doesn't.
    # 3. .sum(): Adds up the results. Since Python treats True as 1 and False as 0, 
    #            this effectively counts the exact number of matches.
    return group["Series_Title"].str.startswith("A").sum()

# Apply the custom function to each group within the 'genres' GroupBy object
genres.apply(beginWithA)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [94]:
# more efficient way

# 1. Create a boolean Series (True if it starts with A, False otherwise)
# 2. Group that boolean Series by the Genre
# 3. Sum the True values (True evaluates to 1, False to 0)

movies["Series_Title"].str.startswith("A").groupby(movies["Genre"]).sum()

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
Name: Series_Title, dtype: int64

In [91]:
def rankMovies(group):
    group["Genre_Rank"] = group["IMDB_Rating"].rank(ascending=False)
    return group

# Use .apply() to execute the function on each group
genres.apply(rankMovies)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Genre_Rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [95]:
# Define a custom function that takes a single DataFrame 'group' as its input
# (In this context, 'group' represents all the movies for one specific genre)
def rankMovies(group):
    
    # 1. group["IMDB_Rating"]: Isolates just the ratings column for this specific genre.
    # 2. .rank(ascending=False): Calculates the numerical rank of those ratings. 
    #    Setting ascending=False means the highest rating gets rank 1, the next highest gets 2, etc.
    # 3. group["Genre_Rank"] = ... : Creates a brand new column named "Genre_Rank" in this 
    #    group's DataFrame and fills it with the ranks we just calculated.
    group["Genre_Rank"] = group["IMDB_Rating"].rank(ascending=False)
    
    # 4. Return the updated group (which now includes the new rank column) back to pandas
    return group

# Use .apply() to execute the function on each group
# .apply() acts as the "manager". It takes your 'rankMovies' function, passes each individual 
# genre group into it one at a time, and then seamlessly combines all the modified groups 
# back together into a single, cohesive DataFrame.
genres.apply(rankMovies)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Genre_Rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [92]:
# efficient approach

# Group by Genre, isolate the rating, and calculate the rank directly
movies["Genre_Rank"] = movies.groupby("Genre")["IMDB_Rating"].rank(ascending=False)

# View the results
display(movies)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,Genre_Rank
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,1.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,2.5
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,2.5
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,147.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,272.5
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,272.5
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,272.5
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,101.0

In [102]:
# Define a function that takes a single DataFrame 'group' as its input
# (In this case, 'group' contains all the movies for one specific genre)
def normalizedIMDB(group):
    
    # MIN-MAX NORMALIZATION:
    # This formula scales all ratings in the group to be exactly between 0 and 1.
    # The lowest rated movie in the genre becomes 0.0, and the highest becomes 1.0.
    
    # 1. group["IMDB_Rating"].min(): Finds the lowest rating in this specific genre.
    # 2. group["IMDB_Rating"].max(): Finds the highest rating in this specific genre.
    # 3. (group["IMDB_Rating"] - min): Calculates how far each rating is from the bottom.
    # 4. (max - min): Calculates the total spread (range) of ratings in this genre.
    
    # We divide step 3 by step 4 and store it in a brand new column:
    group["Normalized_Rating"] = (group["IMDB_Rating"] - group["IMDB_Rating"].min()) / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min()) 
    
    # Return the updated genre DataFrame (now with the new Normalized column)
    return group

# Use .apply() to pass each genre group through the function
# pandas takes the 'genres' GroupBy object, separates it into individual genre DataFrames,
# passes them into 'normalizedIMDB' one by one, and then automatically combines 
# the returned DataFrames back into one large dataset.
genres.apply(normalizedIMDB)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Normalized_Rating
Genre
Action   2        2303232  534858444.0       84.0           1.000000
         5        1642758  377845905.0       94.0           0.928571
         8        2067042  292576195.0       74.0           0.857143
         10       1661481  315544750.0       92.0           0.857143
         13       1485555  342551365.0       87.0           0.785714
...                   ...          ...        ...                ...
Thriller 700        27733   17550741.0       81.0                NaN
Western  12        688390    6100000.0       90.0           1.000000
         48        302844    5321508.0       80.0           0.700000
         115       232772   15000000.0       74.0           0.500000
         691        65659   31800000.0       69.0           0.000000

[1000 rows x 10 columns]

In [101]:
# efficient way 

# Create the new column in one optimized line using transform and a lambda function
movies["Normalized_Rating"] = movies.groupby("Genre")["IMDB_Rating"].transform(
    lambda x: (x - x.min()) / (x.max() - x.min())
)

# View the result
display(movies)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,Genre_Rank,Normalized_Rating
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,1.0,1.000
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1.0,1.000
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0,1.000
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,2.5,0.875
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,2.5,0.875
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,147.0,0.000
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,272.5,0.000
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,272.5,0.000
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,272.5,0.000
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,101.0,0.000

## 🎯 Practice Tasks
- **Level 1 (Easy):** Use `transform` to create a new column `genre_avg_rating` that broadcasts the genre's mean rating to every movie.
- **Level 2 (Medium):** Use `apply` to find the number of movies starting with the letter 'I' for each `genre`.
- **Level 3 (Hard):** Use `apply` to return the **top 2 highest rated movies** for each genre.

1. Use `transform('mean')` on `imdb_rating` grouped by `genre` to create a new column called `genre_avg_rating`. Print the DataFrame to see how the scalar value is broadcasted to every row!
2. Use `apply` with a lambda function to find the number of movies starting with the letter 'I' (e.g., Inception, Interstellar) for each `genre`. (Hint: `lambda x: x.str.startswith('I').sum()`).
3. Group the `ipl` data by `batsman` and use `apply` with a lambda to find the maximum `runs` score within their own group.

## 🏏 13. Real Dataset Practice
**IPL:** Use `transform` to calculate the **average runs scored by each batsman**, and add it as a column `avg_career_runs`. Then, filter for innings where the batsman scored *more* than their career average.

## 🗄️ 14. SQL Equivalent
`transform()` is exactly equivalent to **SQL Window Functions**!
```sql
SELECT *, 
       AVG(imdb_rating) OVER(PARTITION BY genre) as genre_avg_rating
FROM movies;
```

## 🤖 15. Data Science Use Case
**Target Encoding / Group-wise Scaling:** Normalizing numerical features within categorical groups (e.g., scaling salaries within each department) before feeding them into a neural network.

## 🏆 16. Mini Challenge
Use `transform` to calculate the Z-score of `salary` within each `dept`. Then, use boolean indexing to filter and keep only the employees whose salary is > 1 standard deviation above their department's mean.

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ MODULE 3: SOLUTIONS
# ==========================================
# Level 1
movies['genre_avg_rating'] = movies.groupby('genre')['imdb_rating'].transform('mean')
print(movies[['title', 'genre', 'genre_avg_rating']])

# Level 2
print(movies.groupby('genre')['title'].apply(lambda x: x.str.startswith('I').sum()))

# Level 3
print(movies.sort_values('imdb_rating', ascending=False).groupby('genre').head(2))
# Note: Using sort + head is much faster than apply for top N!

# Real Dataset
ipl['avg_career_runs'] = ipl.groupby('batsman')['runs'].transform('mean')
print(ipl[ipl['runs'] > ipl['avg_career_runs']])

# Mini Challenge
employees['salary_z'] = employees.groupby('dept')['salary'].transform(lambda x: (x - x.mean()) / x.std())
print(employees[employees['salary_z'] > 1])
```

</details>

In [17]:
# ==========================================
# 💻 MODULE 3: PRACTICE AREA
# ==========================================
# Level 1: Transform mean
# YOUR CODE HERE:

# Level 2: Apply custom count
# YOUR CODE HERE:

# Level 3: Top 2 movies per genre using apply
# YOUR CODE HERE:

# Real Dataset: Batsman above career average
# YOUR CODE HERE:

# Mini Challenge: Z-score filtering
# YOUR CODE HERE:

In [71]:
# --- EXAMPLE CODE ---
# Normalized IMDB rating group-wise (Z-score concept)
"""movies['rating_normalized'] = movies.groupby('genre')['imdb_rating'].transform(lambda x: x - x.mean())
print("Normalized Ratings (Deviation from Genre Mean):\n", movies[['title_x', 'genre', 'imdb_rating', 'rating_normalized']])
"""
# --- PRACTICE AREA ---
# Task 1: Create 'genre_avg_rating' column using transform('mean')


# Task 2: Use apply to count movies starting with 'I' per genre


# Task 3: Find highest score per batsman in IPL using apply

'movies[\'rating_normalized\'] = movies.groupby(\'genre\')[\'imdb_rating\'].transform(lambda x: x - x.mean())\nprint("Normalized Ratings (Deviation from Genre Mean):\n", movies[[\'title_x\', \'genre\', \'imdb_rating\', \'rating_normalized\']])\n'

# 📘 Module 4: Multi-Column GroupBy & IPL Deep Dive

## 🧠 1. Theory
You can group by multiple columns by passing a **list of column names**. This creates a **MultiIndex (Hierarchical Index)**.

## 💡 2. Mental Model
Grouping by `['Actor', 'Genre']` is like organizing a closet first by **Person**, and then within each person's section, organizing by **Clothing Type**.

## 📊 3. Visual Diagram
```text
groupby(['actor', 'genre'])

actor       genre
Bale        Action     1
Cameron     Sci-Fi     1
DiCaprio    Action     2
```

## 🛠️ 4. Syntax
```python
df.groupby(['col1', 'col2']).agg(...)
```

## 💻 5. Example & 6. Output & 7. Explanation
```python
# Best actor-genre combo by avg metascore
combo = movies.groupby(['actor', 'genre'])['metascore'].mean()
```
**Output:** A Series with a MultiIndex (Actor, Genre).
**Explanation:** Pandas creates a hierarchy. To use this like a normal DataFrame, you must chain `.reset_index()`.

## ⚠️ 8. Common Mistakes & Debugging
**Mistake:** The MultiIndex Trap. After grouping by multiple columns, the result has a MultiIndex. If you try to filter it like a normal DataFrame, it will fail.
**🐛 Debugging Task:** How do you flatten a MultiIndex Series back into a standard DataFrame?
*(Answer: Chain `.reset_index()` at the end of your aggregation!)*

## 🎤 9. Interview Questions & Output Prediction
**Q1: How do you handle missing values in GroupBy?**
> **A:** By default, `groupby()` drops NaN keys. To keep them, use `df.groupby('col', dropna=False)`.

In [109]:
# groupby on multiple columns

duo = movies.groupby(["Director", "Star1"])
# size
duo.size()
# get group
duo.get_group(("Aamir Khan", "Amole Gupte"))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,Genre_Rank,Normalized_Rating
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN,17.0,0.470588

In [111]:
# find most earning director and actor combo
duo["Gross"].sum().sort_values(ascending=False)

Director              Star1
Akira Kurosawa        Toshirô Mifune     2.999877e+09
Anthony Russo         Joe Russo          2.205039e+09
Billy Wilder          William Holden     1.286779e+09
Christopher Nolan     Christian Bale     1.242940e+09
Werner Herzog         Klaus Kinski       1.124605e+09
                                             ...
Jeong-beom Lee        Won Bin            6.460000e+03
Shane Meadows         Paddy Considine    6.013000e+03
Jaco Van Dormael      Jared Leto         3.600000e+03
Thomas Jahn           Til Schweiger      3.296000e+03
Anders Thomas Jensen  Ulrich Thomsen     1.305000e+03
Name: Gross, Length: 898, dtype: float64

In [120]:
# Find the best (in terms of metascore (avg))

movies.groupby(["Star1", "Genre"])["Metascore"].mean().reset_index().sort_values("Metascore", ascending=False).head()

               Star1      Genre  Metascore
606    Peter O'Toole  Adventure      100.0
590     Orson Welles      Drama      100.0
77       Bertil Guve      Drama      100.0
230   Ellar Coltrane      Drama      100.0
329  Humphrey Bogart      Drama      100.0

## 🎯  Practice Tasks
**Level 1 (Easy):** Group by `['actor', 'genre']` and count the number of movies.
**Level 2 (Medium):** Find the most earning `actor` + `director` combo (Sum of `revenue_mil`).
**Level 3 (Hard):** Flatten the MultiIndex from Level 2 using `reset_index()` and sort it to find the highest earning combo.

1. Group `movies` by `['director', 'genre']` and count the number of movies (`size()`).
2. Group `movies` by `['lead_actor', 'genre']` and calculate the mean of `metascore`.
3. Group the `ipl` data by `['batsman', 'bowling_team']`, calculate the sum of `runs`, and chain `.reset_index()` to flatten the result into a clean DataFrame.

## 🏏 13. Real Dataset Practice (IPL Deep Dive)
1. Find **Virat Kohli's record** (total runs) against all teams.
2. Find the batsman with the most number of **4's and 6's in the last 5 overs** (Assume `over_no >= 16`).
3. **Create a custom function** that takes a batsman's name and returns their highest score using `apply` or `agg`.

## 🗄️ 14. SQL Equivalent
```sql
SELECT actor, director, SUM(revenue_mil)
FROM movies
GROUP BY actor, director;
```

## 🤖 15. Data Science Use Case
**Interaction Features:** Creating combined categorical features (e.g., `User_ID` + `Product_Category`) to capture complex relational patterns in recommendation systems.

## 🏆 16. Mini Challenge
Write a Python function `get_highest_score(batsman_name)` that filters the IPL dataset, groups by `match_id`, sums the runs, and returns the maximum. Test it for 'Kohli'.

<details>
<summary>Click for solution</summary>

```
# ==========================================
# ✅ MODULE 4: SOLUTIONS
# ==========================================
# Level 1
print(movies.groupby(['actor', 'genre']).size())

# Level 2 & 3
combo = movies.groupby(['actor', 'director'])['revenue_mil'].sum().reset_index()
print(combo.sort_values('revenue_mil', ascending=False).head(1))

# Real Dataset 1
kohli = ipl[ipl['batsman'] == 'Kohli']
print(kohli.groupby('bowling_team')['runs'].sum())

# Real Dataset 2
death_overs = ipl[ipl['over_no'] >= 16].copy()
death_overs['boundaries'] = death_overs['fours'] + death_overs['sixes']
print(death_overs.groupby('batsman')['boundaries'].sum().idxmax())

# Mini Challenge
def get_highest_score(name):
    player_data = ipl[ipl['batsman'] == name]
    return player_data.groupby('match_id')['runs'].sum().max()

print(f"Kohli's Highest Score: {get_highest_score('Kohli')}")
```

</details>

In [ ]:
# ==========================================
# 💻 MODULE 4: PRACTICE AREA
# ==========================================
# Level 1: Multi-col size
# YOUR CODE HERE:

# Level 2 & 3: Most earning actor-director combo (flattened)
# YOUR CODE HERE:

# Real Dataset 1: Kohli vs teams
# YOUR CODE HERE:

# Real Dataset 2: Death over boundaries (>= 16)
# YOUR CODE HERE:

# Mini Challenge: Custom highest score function
# YOUR CODE HERE:

In [ ]:
# --- EXAMPLE CODE ---
# Best actor-genre combo by avg metascore (flattened)
combo = movies.groupby(['lead_actor', 'genre'])['metascore'].mean().reset_index()
print("Best Actor-Genre Combos:\n", combo.sort_values('metascore', ascending=False).head())

# --- PRACTICE AREA ---
# Task 1: Group by director and genre, and get the size()


# Task 2: Group by lead_actor and genre, get mean of metascore


# Task 3: Find total runs by batsman against each bowling_team (flatten with reset_index)

### IPL Analytics Masterclass

You are the Lead Analyst for an IPL franchise. Put everything you've learned together to generate a report.

Requirements:
1. Find the top 2 batsman in terms of total `runs`.
2. Find the batsman with the absolute maximum number of `sixes`.
3. Find the batsman with the most boundaries (sum of `fours` and `sixes`) strictly in the "death overs" (Assume `over_no >= 16`).
4. Find Virat Kohli's total `runs` record against all individual bowling teams.

In [ ]:
# --- PRACTICE AREA: MINI PROJECT ---
print("--- 1. Top 2 Batsman by Total Runs ---")
# Your code here


print("\n--- 2. Batsman with Max Sixes ---")
# Your code here


print("\n--- 3. Best Death Over Hitter (Overs >= 16) ---")
# Your code here


print("\n--- 4. Kohli's Record vs All Teams ---")
# Your code here

# 🎉 Congratulations!
You have mastered **Pandas Part 4: GroupBy & Aggregations**. 

You now know how to:

✅ Split, Apply, and Combine data.

✅ Use `agg()` for complex, multi-column aggregations.

✅ Master `transform()` and `apply()` for group-level feature engineering.

✅ Handle Multi-Index GroupBy operations.

✅ Perform real-world sports analytics (IPL).

### 🚀 Next Steps
You are now ready for **Pandas Part 5: Merging, Joining, and Concatenating** – learning how to combine multiple DataFrames together like a SQL Database!